Repository learningequality/studio, pull requests merged in 2018-10, with the labels that each got.

#755 User docs update
  docs/_static/theme_overrides.css
  docs/access_studio.rst
  docs/add_content.rst
  docs/appendix.rst
  docs/conf.py
  docs/img/account-settings.png
  docs/img/add-more-files.png
  docs/img/add-subtopics.png
  docs/img/add-thumb.png
  docs/img/answer-editor.png
  docs/img/channel-details.gif
  docs/img/channel-languages-preview.png
  docs/img/channel-pane-details.png
  docs/img/channel-source-id-token.gif
  docs/img/channel-type.png
  docs/img/channelID1.png
  docs/img/channelID2.png
  docs/img/channelID3.png
  docs/img/clipboard.png
  docs/img/coach-resource.png
  docs/img/coach-resource2.png
  docs/img/create-account.png
  docs/img/delete-content.png
  docs/img/edit-channel-content-tools.png
  docs/img/edit-channel-details.png
  docs/img/edit-content-questions.png
  docs/img/edit-topics.png
  docs/img/edit-upload.png
  docs/img/generate-thumbnails.jpg
  docs/img/import-search.png
  docs/img/profile-settings.png
  docs/img/reorder-answers.png
  docs/img/request-more-storage-1.png
  docs/img/request-more-storage-2.png
  docs/img/request-more-storage-3.png
  docs/img/settings.png
  docs/img/storage-usage.png
  docs/img/tokens-settings.png
  docs/index.rst
  docs/kolibri_channels.rst
  docs/manage_content.rst
  docs/publish_channel.rst
  docs/share_channels.rst
  docs/working_channels.rst
Labels: enhancement

#1003 admin page refactor
  Pipfile
  Pipfile.lock
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/static/js/administration/hbtemplates/admin_area.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/channel_counts.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/channel_item.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/channel_list.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/channel_tab.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/email_modal.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/user_item.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/user_list.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/user_tab.handlebars
  contentcuration/contentcuration/static/js/administration/router.js
  contentcuration/contentcuration/static/js/administration/views.js
  contentcuration/contentcuration/static/js/bundle_modules/administration.js
  contentcuration/contentcuration/static/js/edit_channel/admin/hbtemplates/admin_area.handlebars
  contentcuration/contentcuration/static/js/edit_channel/admin/hbtemplates/channel_list.handlebars
  contentcuration/contentcuration/static/js/edit_channel/admin/hbtemplates/channel_tab.handlebars
  contentcuration/contentcuration/static/js/edit_channel/admin/hbtemplates/user_list.handlebars
  contentcuration/contentcuration/static/js/edit_channel/admin/hbtemplates/user_tab.handlebars
  contentcuration/contentcuration/static/js/edit_channel/admin/views.js
  contentcuration/contentcuration/static/js/edit_channel/models.js
  contentcuration/contentcuration/static/js/edit_channel/new_channel/views.js
  contentcuration/contentcuration/static/js/edit_channel/router.js
  contentcuration/contentcuration/static/js/edit_channel/views.js
  contentcuration/contentcuration/static/less/admin.less
  contentcuration/contentcuration/static/less/admin_grid.less
  contentcuration/contentcuration/templates/administration.html
  contentcuration/contentcuration/tests/test_admin_user_channel_apis.py
  contentcuration/contentcuration/tests/test_authentication.py
  contentcuration/contentcuration/tests/testdata.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/admin.py
  package.json
  webpack.config.js
  yarn.lock
Labels: needs review

#1034 Avoid saving existing exercises on GCS again
  contentcuration/contentcuration/tests/test_gcs_storage.py
  contentcuration/contentcuration/utils/gcs_storage.py
Labels: needs review

#1040 Frontend State Refactor, Step 1
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/static/js/administration/router.js
  contentcuration/contentcuration/static/js/administration/views.js
  contentcuration/contentcuration/static/js/bundle_modules/channel_edit.js
  contentcuration/contentcuration/static/js/edit_channel/__tests__/state.spec.js
  contentcuration/contentcuration/static/js/edit_channel/archive/views.js
  contentcuration/contentcuration/static/js/edit_channel/channel_settings/views.js
  contentcuration/contentcuration/static/js/edit_channel/constants/ContentKinds.js
  contentcuration/contentcuration/static/js/edit_channel/constants/FormatPresets.js
  contentcuration/contentcuration/static/js/edit_channel/constants/Languages.js
  contentcuration/contentcuration/static/js/edit_channel/constants/Licenses.js
  contentcuration/contentcuration/static/js/edit_channel/constants/MasteryModels.js
  contentcuration/contentcuration/static/js/edit_channel/constants/Roles.js
  contentcuration/contentcuration/static/js/edit_channel/constants/index.js
  contentcuration/contentcuration/static/js/edit_channel/details/views.js
  contentcuration/contentcuration/static/js/edit_channel/export/views.js
  contentcuration/contentcuration/static/js/edit_channel/file_upload/views.js
  contentcuration/contentcuration/static/js/edit_channel/image/views.js
  contentcuration/contentcuration/static/js/edit_channel/import/vuex/importGetters.js
  contentcuration/contentcuration/static/js/edit_channel/import/vuex/importUtils.js
  contentcuration/contentcuration/static/js/edit_channel/information/views.js
  contentcuration/contentcuration/static/js/edit_channel/models.js
  contentcuration/contentcuration/static/js/edit_channel/move/views.js
  contentcuration/contentcuration/static/js/edit_channel/new_channel/views.js
  contentcuration/contentcuration/static/js/edit_channel/preview/views.js
  contentcuration/contentcuration/static/js/edit_channel/queue/views.js
  contentcuration/contentcuration/static/js/edit_channel/related/views.js
  contentcuration/contentcuration/static/js/edit_channel/router.js
  contentcuration/contentcuration/static/js/edit_channel/share/views.js
  contentcuration/contentcuration/static/js/edit_channel/state.js
  contentcuration/contentcuration/static/js/edit_channel/sync/views.js
  contentcuration/contentcuration/static/js/edit_channel/tree_edit/views.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/views.js
  contentcuration/contentcuration/static/js/edit_channel/utils/drag_drop.js
  contentcuration/contentcuration/static/js/edit_channel/utils/string_helper.js
  contentcuration/contentcuration/static/js/edit_channel/utils/workspace_manager.js
  contentcuration/contentcuration/static/js/edit_channel/views.js
  contentcuration/contentcuration/static/js/edit_channel/vuexModules/channel.js
  contentcuration/contentcuration/templates/channel_edit.html
  contentcuration/contentcuration/templates/channel_list.html
  contentcuration/contentcuration/views/base.py
  deploy/generatejsconstantfiles.py
  jest_config/jest.conf.js
  jest_config/setup.js
  package.json
  yarn.lock
Labels: needs review

#1009 [WIP] Add initial version of set_content_mimetypes mgmt command
  contentcuration/contentcuration/management/commands/set_content_mimetypes.py
Labels: WIP

#1039 Admin page collapsed page navigation
  contentcuration/contentcuration/static/js/administration/hbtemplates/channel_tab.handlebars
  contentcuration/contentcuration/static/js/administration/hbtemplates/user_tab.handlebars
  contentcuration/contentcuration/static/js/administration/router.js
  contentcuration/contentcuration/static/js/administration/views.js
  contentcuration/contentcuration/static/js/edit_channel/models.js
  contentcuration/contentcuration/static/less/admin.less
  contentcuration/contentcuration/static/less/admin_grid.less
Labels: enhancement
