Repository learningequality/studio, pull requests merged in 2019-12, with the labels that each got.

#1701 Fix null db entries + not-null field requirement mismatch issues.
  contentcuration/contentcuration/migrations/0101_extra_fields_json_field.py
  contentcuration/contentcuration/migrations/0109_auto_20191202_1759.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/serializers.py
Labels: qa-ready

#1706 Fix the deployment by adding in a missing manifest key
  k8s/helm-deploy.sh
  k8s/templates/studio-deployment.yaml
  k8s/templates/studio-secrets.yaml
Labels: qa-ready

#1704 Add a frontend connection pool for pgbouncer, and miscellaneous optimizations
  contentcuration/contentcuration/views/base.py
  k8s/templates/_helpers.tpl
  k8s/templates/frontend-pgbouncer.yaml
  k8s/templates/studio-deployment.yaml
  k8s/values-prod-config.yaml
  k8s/values.yaml
Labels: qa-ready

#1688 [PoC] TUI Editor + inline formulas editing - (B) Editing in the menu only
  contentcuration/contentcuration/management/commands/setup.py
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AnswersEditor/AnswersEditor.spec.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AnswersEditor/AnswersEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentEditor/AssessmentEditor.spec.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentEditor/AssessmentEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentEditor/__snapshots__/AssessmentEditor.spec.js.snap
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentItemEditor/AssessmentItemEditor.spec.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentItemEditor/__snapshots__/AssessmentItemEditor.spec.js.snap
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentItemPreview/AssessmentItemPreview.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/AssessmentItemPreview/__snapshots__/AssessmentItemPreview.spec.js.snap
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/Formula/Formula.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/FormulasMenu/FormulasMenu.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/FormulasMenu/symbols.json
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/HintsEditor/HintsEditor.spec.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/HintsEditor/HintsEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/HintsEditor/__snapshots__/HintsEditor.spec.js.snap
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownEditor/__mocks__/MarkdownEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownViewer/MarkdownViewer.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownViewer/__mocks__/MarkdownViewer.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/__tests__/extensions/formulas/formula-html-to-md.spec.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/buttons.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/constants.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/formulas/formula-html-to-md.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/formulas/formulas.css
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/formulas/formulas.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/formulas/index.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/formulas/markdown-it-formula.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/formulas/toolbar-icon-formulas.svg
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/image-upload/image-upload.css
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/image-upload/image-upload.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/image-upload/index.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/image-upload/toolbar-icon-image-upload.svg
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/minimize/index.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/minimize/minimize.css
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/minimize/minimize.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/minimize/toolbar-icon-minimize.svg
  contentcuration/contentcuration/static/js/edit_channel/uploader/directives/click-outside.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/views/__tests__/AssessmentView.spec.js
  contentcuration/contentcuration/static/js/sandbox/Sandbox.vue
  contentcuration/contentcuration/static/js/utils/mathquill.js
  package.json
  webpack.config.js
  yarn.lock
Labels: frontend, qa-ready, vueify

#1723 Change pgbouncer settings
  contentcuration/contentcuration/settings.py
  k8s/templates/frontend-pgbouncer.yaml
  k8s/values-prod-config.yaml
  k8s/values.yaml
Labels: sysops

#1724 Temporarily disable pgbouncer until we can fix the connection errors …
  contentcuration/contentcuration/settings.py
  k8s/templates/frontend-pgbouncer.yaml
  k8s/templates/studio-deployment.yaml
Labels: qa-ready
