Repository learningequality/studio, pull requests merged in 2019-08, with the labels that each got.

#1563 Flesh out our liveness and readiness probes
  k8s/templates/studio-deployment.yaml
Labels: qa-ready

#1571 Disable video thumbnails
  contentcuration/contentcuration/utils/files.py
Labels: CHANGELOG

#1576 Fixed icon encodings not getting saved
  contentcuration/contentcuration/tests/test_exportchannel.py
  contentcuration/contentcuration/utils/publish.py
Labels: CHANGELOG

#1573 Switched channel id to token in published email text
  contentcuration/contentcuration/templates/registration/channel_published_email.txt
  contentcuration/contentcuration/utils/publish.py
Labels: CHANGELOG

#1518 Reduce permissions overhead where possible
  contentcuration/contentcuration/views/nodes.py
Labels: qa-ready

#1344 Migrate `ContentNode.extra_fields` to type `JSONField`
  contentcuration/contentcuration/api.py
  contentcuration/contentcuration/management/commands/setup.py
  contentcuration/contentcuration/migrations/0101_extra_fields_json_field.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/static/js/edit_channel/models.js
  contentcuration/contentcuration/tests/test_channel_model.py
  contentcuration/contentcuration/tests/test_exportchannel.py
  contentcuration/contentcuration/tests/test_extra_fields_json_field_migration.py
  contentcuration/contentcuration/tests/test_thumbnail_encoding_json_migration.py
  contentcuration/contentcuration/tests/test_user.py
  contentcuration/contentcuration/tests/testdata.py
  contentcuration/contentcuration/tests/utils.py
  contentcuration/contentcuration/utils/import_tools.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/views/internal.py
  deploy/chaos/loadtest/prep.py
Labels: high priority

#1500 Add subtitle conversion on upload
  Pipfile
  Pipfile.lock
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/static/js/edit_channel/constants/FormatPresets.js
  contentcuration/contentcuration/static/js/edit_channel/constants/index.js
  contentcuration/contentcuration/static/js/edit_channel/file_upload/hbtemplates/format_multilanguage_item.handlebars
  contentcuration/contentcuration/static/js/edit_channel/file_upload/views.js
  contentcuration/contentcuration/static/less/file-uploader.less
  contentcuration/contentcuration/tests/test_files.py
  contentcuration/contentcuration/tests/test_models.py
  contentcuration/contentcuration/tests/testdata.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/files.py
  docker-compose.alt.yml
Labels: CHANGELOG, docs
