Repository learningequality/studio, pull requests merged in 2019-07, with the labels that each got.

#1481 Remove unused jsi18n reference and use static jsreverse in production.
  contentcuration/contentcuration/templates/base.html
  contentcuration/contentcuration/urls.py
  deploy/chaos/loadtest/locustfile.py
Labels: optimization, qa-ready

#1505 Make move nodes ops appear synchronous
  contentcuration/contentcuration/static/js/edit_channel/models.js
  contentcuration/contentcuration/static/js/edit_channel/sharedComponents/ProgressOverlay.vue
  contentcuration/contentcuration/static/js/edit_channel/vuexModules/asyncTask.js
  contentcuration/contentcuration/utils/nodes.py
Labels: UX, enhancement, qa-ready

#1507 Increase tag length to 50
  contentcuration/contentcuration/migrations/0099_auto_20190715_2201.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/test_contentnodes.py
Labels: CHANGELOG

#1458 Fix prober url and add clean-ups to Dockerfile
  deploy/probers/base.py
  deploy/probers/login_page_probe.py
  deploy/probers/postmark_api_probe.py
  docker-compose.yml
  docker/Dockerfile.demo
  docker/Dockerfile.dev
  docker/entrypoint.py
  k8s/images/app/Dockerfile
Labels: sysops

#1508 Limit Celery worker processes as we do with Gunicorn
  Makefile
Labels: optimization

#1509 Set studio's frontend and worker pods to a guaranteed allocation of 0.5 CPU and 2Gi of RAM
  k8s/templates/studio-deployment.yaml
Labels: qa-ready

#1503 Display an operation finished message when the operation completes.
  contentcuration/contentcuration/static/js/edit_channel/sharedComponents/ProgressOverlay.vue
  contentcuration/contentcuration/static/js/edit_channel/sharedComponents/__tests__/progressOverlay.spec.js
Labels: UX, frontend

#1515 Quick fixes for issues identified during bash
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/static/js/edit_channel/models.js
  contentcuration/contentcuration/static/js/edit_channel/publish/tests/data.js
  contentcuration/contentcuration/static/js/edit_channel/publish/tests/publishModal.spec.js
  contentcuration/contentcuration/static/js/edit_channel/publish/views/PublishModal.vue
  contentcuration/contentcuration/static/js/edit_channel/router.js
  contentcuration/contentcuration/static/js/edit_channel/tree_edit/views.js
  contentcuration/contentcuration/static/js/edit_channel/vuexModules/asyncTask.js
  contentcuration/contentcuration/static/js/edit_channel/vuexModules/channel.js
  contentcuration/contentcuration/templates/channel_edit.html
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/nodes.py
Labels: qa-ready

#1435 Move DB migrations to a kubernetes job
  Makefile
  contentcuration/contentcuration/management/commands/setup.py
  k8s/templates/studio-deployment.yaml
Labels: qa-ready

#1534 Fix issue with two migrations numbered 0099.
  contentcuration/contentcuration/migrations/0100_calculate_included_languages.py
  contentcuration/contentcuration/tests/test_included_languages_migration.py
Labels: qa-ready

#1535 Commit translations to the repo
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelListPage.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelSetList.vue
  contentcuration/locale/ar_SA/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/ar_SA/LC_MESSAGES/django.mo
  contentcuration/locale/ar_SA/LC_MESSAGES/django.po
  contentcuration/locale/en/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/en/LC_MESSAGES/django.mo
  contentcuration/locale/en/LC_MESSAGES/django.po
  contentcuration/locale/es_ES/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_ES/LC_MESSAGES/django.mo
  contentcuration/locale/es_ES/LC_MESSAGES/django.po
  contentcuration/locale/es_MX/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_MX/LC_MESSAGES/django.mo
  contentcuration/locale/es_MX/LC_MESSAGES/django.po
  contentcuration/locale/fr_FR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/django.mo
  contentcuration/locale/fr_FR/LC_MESSAGES/django.po
  contentcuration/locale/hi_IN/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/hi_IN/LC_MESSAGES/django.mo
  contentcuration/locale/hi_IN/LC_MESSAGES/django.po
  deploy/downloadmessages.py
  docker/Dockerfile.demo
  k8s/images/app/Dockerfile
  package.json
Labels: qa-ready

#1538 Create base fallback language for Spanish
  contentcuration/contentcuration/settings.py
  contentcuration/locale/es/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es/LC_MESSAGES/django.mo
  contentcuration/locale/es/LC_MESSAGES/django.po
  contentcuration/locale/es_ES/LC_MESSAGES/django.po
  contentcuration/locale/es_MX/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_MX/LC_MESSAGES/django.mo
Labels: CHANGELOG

#1529 Fix select styling and clipboard entry title font properties…
  contentcuration/contentcuration/static/less/queue.less
  contentcuration/contentcuration/static/less/styles.less
  package.json
  postcss.config.js
  webpack.config.js
  yarn.lock
Labels: qa-ready

#1533 Pin Summernote version to 0.8.10
  package.json
  yarn.lock
Labels: frontend, needs review
