Repository learningequality/studio, pull requests merged in 2019-05, with the labels that each got.

#1360 Add babel-polyfill to base JS module.
  package.json
  webpack.config.js
  yarn.lock
Labels: frontend, needs review, qa-ready

#1367 [Fixes #1299] Restore thumbnail data to public channels API.
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/tests/test_public_api.py
  contentcuration/contentcuration/views/public.py
Labels: CHANGELOG, qa-ready

#1369 Remove thumbnail cropping, and default thumbnail aspect ratio to 16:9
  .idea/studio.iml
  contentcuration/contentcuration/static/img/kolibri_placeholder.png
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelItem.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelMetadataSection.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_set/views/ChannelItem.vue
  contentcuration/contentcuration/static/js/edit_channel/details/hbtemplates/details_view.handlebars
  contentcuration/contentcuration/static/js/edit_channel/image/views.js
  contentcuration/contentcuration/static/less/channel_list.less
  contentcuration/contentcuration/static/less/channel_settings.less
  contentcuration/contentcuration/static/less/details.less
  contentcuration/contentcuration/static/less/queue.less
  contentcuration/contentcuration/utils/files.py
Labels: qa-ready

#1366 Update document thumbnail order
  Pipfile.lock
  contentcuration/contentcuration/static/js/edit_channel/constants/ContentKinds.js
  contentcuration/contentcuration/static/js/edit_channel/constants/FormatPresets.js
  contentcuration/contentcuration/static/js/edit_channel/constants/Languages.js
Labels: CHANGELOG

#1308 Slideshow Import from Ricecooker & Publish to Kolibri
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  contentcuration/contentcuration/management/commands/exportchannel.py
  contentcuration/contentcuration/migrations/0098_auto_20190424_1709.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/static/js/edit_channel/file_upload/views.js
  contentcuration/contentcuration/static/js/edit_channel/import/util.js
  contentcuration/contentcuration/static/js/edit_channel/preview/hbtemplates/preview_templates/slideshow.handlebars
  contentcuration/contentcuration/static/js/edit_channel/preview/views.js
  contentcuration/contentcuration/static/js/edit_channel/utils/d3_helper.js
  contentcuration/contentcuration/static/js/edit_channel/utils/string_helper.js
  contentcuration/contentcuration/static/js/handlebars/helpers.js
  contentcuration/contentcuration/static/less/content-container.less
  contentcuration/contentcuration/static/less/global-variables.less
  contentcuration/contentcuration/tests/test_exportchannel.py
  contentcuration/contentcuration/utils/export_writer.py
  contentcuration/contentcuration/utils/nodes.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/views/internal.py
  contentcuration/kolibri_content/migrations/0005_auto_20190424_1709.py
Labels: needs review, qa-ready

#1374 Manage Channel List Page with Vue Router
  contentcuration/contentcuration/static/js/bundle_modules/ChannelEditIndex.vue
  contentcuration/contentcuration/static/js/bundle_modules/channel_edit.js
  contentcuration/contentcuration/static/js/bundle_modules/channel_list.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/mixins.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelEditor.spec.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelItem.spec.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelListPage.spec.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelDetailsPanel.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelEditor.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelList.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelListPage.vue
  contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/actions.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/getters.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/mutations.js
  contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/store.js
  contentcuration/contentcuration/static/js/edit_channel/router.js
  contentcuration/contentcuration/static/less/channel_list.less
  contentcuration/contentcuration/templates/channel_list.html
  webpack.config.js
Labels: qa-ready

#1365 Docker Invalidation FIxes
  docker/Dockerfile.dev
Labels: sysops

#1391 Move newrelic initialization to the start of WSGI.
  contentcuration/contentcuration/wsgi.py
Labels: qa-ready

#1403 [Fixes #1392] Tweak thumbnail display in channel list and detail edit…
  contentcuration/contentcuration/static/less/channel_list.less
  contentcuration/contentcuration/static/less/images.less
Labels: UX, qa-ready
