Repository learningequality/studio, pull requests merged in 2019-06, with the labels that each got.

#1449 Handle the case where the topic kind was already created.
  contentcuration/contentcuration/tests/test_included_languages_migration.py
Labels: tests

#1462 Added content nodes to global state
  contentcuration/contentcuration/static/js/edit_channel/__tests__/ContentNodesState.spec.js
  contentcuration/contentcuration/static/js/edit_channel/state.js
  contentcuration/contentcuration/static/js/edit_channel/vuexModules/contentNodes.js
Labels: CHANGELOG

#1472 Move channel import functionality to module
  contentcuration/contentcuration/management/commands/restore_channel.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tests/test_restore_channel.py
  contentcuration/contentcuration/utils/import_tools.py
Labels: WIP
