Repository learningequality/studio, pull requests merged in 2020-12, with the labels that each got.

#2543 Fix hierarchy scrolling and raise resizeable drawer border
  .pre-commit-config.yaml
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/shared/views/ResizableNavigationDrawer.vue
Labels: P1 - important, frontend, needs review

#2600 makes update banner hidden for view-only channels
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
Labels: needs review

#2625 Latest French and Arabic i18n
  contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
Labels: needs review

#2624 Better error handling in change event handlers
  contentcuration/contentcuration/migrations/0124_auto_20201204_1645.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/test_contentnodes.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
  contentcuration/contentcuration/viewsets/sync/utils.py
Labels: needs review

#2613 Filter channelsetlist by user
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/actions.js
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/viewsets/channelset.py
Labels: needs review

#2498 Fix assessment item reordering
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemToolbar.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentTab/AssessmentTab.vue
  contentcuration/contentcuration/frontend/channelEdit/utils.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/mutations.js
Labels: frontend

#2607 annotate after paginate Admin channels and users
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
  contentcuration/contentcuration/frontend/administration/vuex/channelAdmin/actions.js
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/tests/viewsets/test_channel.py
  contentcuration/contentcuration/utils/channel.py
  contentcuration/contentcuration/utils/user.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/user.py
Labels: needs review

#2612 Being more semantic when annotate after paginate is used
  contentcuration/search/viewsets/contentnode.py
Labels: enhancement

#2637 Ensure window.Urls has correct language code & browser lang is respected
  Makefile
  contentcuration/contentcuration/context_processors.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/templates/base.html
Labels: needs review

#2626 Optimize catalog filters and pagination
  contentcuration/contentcuration/utils/pagination.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/search/viewsets/contentnode.py
Labels: needs review

#2623 withChangeTracker bugfix - call hideCallback in snackbar if it exists
  contentcuration/contentcuration/frontend/shared/vuex/snackbar/index.js
Labels: needs review

#2635 Don't let errors happen when Sentry or user are not initialized.
  contentcuration/contentcuration/templates/base.html
Labels: needs review

#2618 Fix concurrent copying
  contentcuration/contentcuration/db/models/manager.py
Labels: needs review

#2606 `complete` validation improvements
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentTab/AssessmentTab.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/__tests__/mutations.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/shared/utils/validation.js
  contentcuration/contentcuration/frontend/shared/utils/validation.spec.js
  contentcuration/contentcuration/management/commands/setup.py
  contentcuration/contentcuration/utils/db_tools.py
Labels: needs review

#2653 Remove order parameter admin view
  contentcuration/contentcuration/frontend/administration/vuex/channelAdmin/actions.js
  contentcuration/contentcuration/frontend/administration/vuex/userAdmin/actions.js
  contentcuration/contentcuration/utils/pagination.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/user.py
Labels: needs review

#2649 Fix clipboard move action visibility
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/shared/views/LazyListGroup.vue
Labels: javascript, needs review

#2662 Fixes external link issues and sometimes incorrect imported channel name
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/shared/views/ActionLink.vue
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: javascript, needs review

#2643 New channel modal toggle tabs
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelList/router.js
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
  contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelModal.spec.js
Labels: needs review

#2647 First pass service worker with automatic reload on update.
  contentcuration/contentcuration/frontend/serviceWorker/index.js
  contentcuration/contentcuration/frontend/shared/__mocks__/urls.js
  contentcuration/contentcuration/frontend/shared/app.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/frontend/shared/urls.js
  contentcuration/contentcuration/frontend/shared/utils/globalThis.js
  contentcuration/contentcuration/static/img/kolibri-logo.png
  contentcuration/contentcuration/templates/base.html
  contentcuration/contentcuration/templates/pwa/manifest.json
  contentcuration/contentcuration/templates/pwa/service_worker.js
  contentcuration/contentcuration/tests/test_urlendpoints.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/pwa.py
  jest_config/setup.js
  package.json
  webpack.config.js
  yarn.lock
Labels: needs review

#2693 Changing languages
  contentcuration/contentcuration/context_processors.py
  contentcuration/contentcuration/frontend/accounts/pages/Main.vue
  contentcuration/contentcuration/frontend/shared/i18n/index.js
  contentcuration/contentcuration/frontend/shared/languageSwitcher/LanguageSwitcherList.vue
  contentcuration/contentcuration/frontend/shared/languageSwitcher/LanguageSwitcherModal.vue
  contentcuration/contentcuration/frontend/shared/languageSwitcher/language-names.scss
  contentcuration/contentcuration/frontend/shared/languageSwitcher/mixin.js
  contentcuration/contentcuration/frontend/shared/views/AppBar.vue
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/templates/base.html
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/i18n.py
  contentcuration/contentcuration/views/base.py
  contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/en/LC_MESSAGES/django.po
  contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/language_info.json
  contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
Labels: needs review

#2677 Don't try to delete a channel that has not been committed to the DB yet.
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Labels: needs review
