Repository learningequality/studio, pull requests merged in 2020-03, with the labels that each got.

#1781 Channel edit page layout
  contentcuration/contentcuration/frontend/channelEdit/constants.js
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelNavigationDrawer.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelDetailsModal.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelModal.vue
  contentcuration/contentcuration/frontend/shared/views/IconButton.vue
  contentcuration/contentcuration/frontend/shared/views/ResizableNavigationDrawer.vue
  contentcuration/contentcuration/frontend/shared/views/ToolBar.vue
  contentcuration/contentcuration/frontend/shared/views/icons/collapseAllIcon.vue
  contentcuration/contentcuration/frontend/shared/views/icons/viewOnlyIcon.vue
  contentcuration/contentcuration/frontend/shared/vuetify/icons.js
  contentcuration/contentcuration/frontend/shared/vuetify/theme.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/views/EditModal.vue
Labels: qa-ready

#1762 Move static output dir to contentcuration/static
  .gitignore
  Makefile
  contentcuration/contentcuration/settings.py
  webpack.config.js
Labels: qa-ready

#1800 Switched get_node_ancestors on serializer to use metadata annotations
  contentcuration/contentcuration/node_metadata/annotations.py
  contentcuration/contentcuration/serializers.py
Labels: qa-ready

#1797 More updates to channel edit page
  contentcuration/contentcuration/frontend/channelEdit/views/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FilePreview.vue
  contentcuration/contentcuration/frontend/channelEdit/views/publish/PublishModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/publish/PublishView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/publish/PublishingOverlay.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/shared/mixins.js
  contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
  contentcuration/contentcuration/frontend/shared/views/ContextMenu.vue
  contentcuration/contentcuration/frontend/shared/views/IconButton.vue
  contentcuration/contentcuration/frontend/shared/views/icons/collapseAllIcon.vue
  contentcuration/contentcuration/frontend/shared/views/icons/viewOnlyIcon.vue
  contentcuration/contentcuration/frontend/shared/vuex/baseStore.js
  contentcuration/contentcuration/frontend/shared/vuex/contextMenu/index.js
  contentcuration/contentcuration/static/js/edit_channel/publish/tests/data.js
  contentcuration/contentcuration/static/js/edit_channel/publish/tests/publishModal.spec.js
  contentcuration/contentcuration/static/js/edit_channel/publish/tests/publishStore.spec.js
  contentcuration/contentcuration/static/js/edit_channel/publish/tests/publishView.spec.js
  contentcuration/contentcuration/static/js/edit_channel/publish/tests/publishWrapper.spec.js
  contentcuration/contentcuration/static/js/edit_channel/publish/views/PublishWrapper.vue
  contentcuration/contentcuration/static/js/edit_channel/router.js
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/tree.py
Labels: qa-ready

#1809 Fixes duplication of children ID's
  contentcuration/contentcuration/db/models/aggregates.py
  contentcuration/contentcuration/static/js/edit_channel/models.js
  contentcuration/contentcuration/views/base.py
Labels: javascript, needs review, performance issue, qa-ready

#1804 Vueified trash modal
  contentcuration/contentcuration/frontend/channelEdit/components/ResourceDrawer.vue
  contentcuration/contentcuration/frontend/channelEdit/constants.js
  contentcuration/contentcuration/frontend/channelEdit/move/MoveModal.vue
  contentcuration/contentcuration/frontend/channelEdit/move/NewTopicModal.vue
  contentcuration/contentcuration/frontend/channelEdit/move/__tests__/moveModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/move/__tests__/newTopicModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/getters.js
  contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
  contentcuration/contentcuration/frontend/shared/views/ContentNodeIcon.vue
  contentcuration/contentcuration/frontend/shared/views/GlobalSnackbar.vue
  contentcuration/contentcuration/frontend/shared/views/ToolBar.vue
  contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
  contentcuration/contentcuration/viewsets/channel.py
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: qa-ready

#1787 Related resources
  .babelrc
  contentcuration/contentcuration/frontend/channelEdit/components/AddRelatedResourcesModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/NodeTreeNavigation.vue
  contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesList/RelatedResourcesList.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesList/RelatedResourcesList.vue
  contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.vue
  contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/related-resources-preview.png
  contentcuration/contentcuration/frontend/channelEdit/constants.js
  contentcuration/contentcuration/frontend/channelEdit/pages/AddNextStepsModal.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/AddPreviousStepsModal.vue
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/getters.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/mutations.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/shared/__tests__/utils.spec.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/utils.js
  contentcuration/contentcuration/frontend/shared/views/icons/lightBulbIcon.vue
  contentcuration/contentcuration/frontend/shared/vuetify/icons.js
  contentcuration/contentcuration/management/commands/setup.py
  contentcuration/contentcuration/static/js/edit_channel/uploader/constants.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/tests/editView.spec.js
  contentcuration/contentcuration/static/js/edit_channel/uploader/views/EditModal.vue
  contentcuration/contentcuration/static/js/edit_channel/uploader/views/EditView.vue
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
Labels: frontend, needs review, qa-ready, vueify

#1825 Change from uglify to terser.
  package.json
  webpack.config.js
  yarn.lock
Labels: qa-ready

#1822 Library-only mode
  contentcuration/contentcuration/catalog_settings.py
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/templates/catalog.html
  contentcuration/contentcuration/templates/channel_list.html
  contentcuration/contentcuration/utils/files.py
  contentcuration/contentcuration/views/base.py
Labels: WIP, qa-ready
