Repository learningequality/studio, pull requests merged in 2020-11, with the labels that each got.

#2499 Fix data flow issues
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeChangedIcon.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/detailsTabView.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadItem.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/getters.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: needs review

#2505 Add preemptive lock for node deletion.
  contentcuration/contentcuration/models.py
Labels: needs review

#2516 Clipboard deletion
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/TopicNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/mixins.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/utils.js
Labels: needs review

#2489 Ensure that topics load when restoring from trash
  contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
Labels: frontend, needs review

#2518 Fix typos in indexes and migrations.
  contentcuration/contentcuration/migrations/0121_auto_20200917_1912.py
  contentcuration/contentcuration/migrations/0122_assessment_id_index.py
  contentcuration/contentcuration/models.py
Labels: needs review

#2503 Associate uploaded exercise images with assessment items on save
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/index.js
  contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/viewsets/assessmentitem.py
  contentcuration/contentcuration/viewsets/contentnode.py
  jest_config/setup.js
Labels: needs review

#2530 make options icon always visible in channel view
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
Labels: needs review

#2532 Update arguments passed to checkSavingProgress so saving indicator shows
  contentcuration/contentcuration/frontend/channelEdit/components/edit/SavingIndicator.vue
Labels: needs review

#2534 Update obsolete mastery model type field in the development server setup
  contentcuration/contentcuration/utils/db_tools.py
Labels: needs review

#2519 Preview resources within clipboard, and be less aggressive with preloading clipboard children
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/mixins.js
  contentcuration/contentcuration/frontend/channelEdit/components/ResourceDrawer.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/utils.js
  contentcuration/contentcuration/frontend/shared/views/ResizableNavigationDrawer.vue
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/getters.js
Labels: frontend, javascript, needs review, optimization, qa-ready, vueify

#2490 Clear client data when an account switched
  contentcuration/contentcuration/frontend/administration/vuex/channelAdmin/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/administration/vuex/userAdmin/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/channelItem.spec.js
  contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
  contentcuration/contentcuration/frontend/channelList/vuex/channelList/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
  contentcuration/contentcuration/frontend/settings/vuex/index.js
  contentcuration/contentcuration/frontend/shared/__tests__/app.spec.js
  contentcuration/contentcuration/frontend/shared/app.js
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/views/AppBar.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PolicyUpdates.vue
  contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/session/index.js
Labels: needs review

#2541 Fix isNew references
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/utils.js
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
Labels: needs review

#2528 Trigger content node operations off drag and drop events
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/constants.js
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/base.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/collection.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/constants.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/handle.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/item.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/region.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/utils.js
  contentcuration/contentcuration/frontend/shared/views/LazyListGroup.vue
  contentcuration/contentcuration/frontend/shared/views/draggable/DraggablePlaceholder.vue
  contentcuration/contentcuration/frontend/shared/vuetify/theme.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/constants.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/mutations.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/mutations.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/utils.js
Labels: UX, frontend, javascript, needs review, qa-ready

#2535 Stop repeating policy modals on Firefox
  contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.spec.js
Labels: qa-ready

#2588 Throw a big error if try to move a child to be its own parent
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
Labels: needs review

#2597 update terms of service and privacy policy dates
  contentcuration/contentcuration/frontend/shared/constants.js
Labels: needs review

#2591 Encode delimiter as bytes since we are dealing with a bytestring
  contentcuration/contentcuration/utils/publish.py
Labels: qa-ready

#2511 Annotate after paginate (and some more stuff)
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/actions.js
  contentcuration/search/viewsets/contentnode.py
Labels: needs review

#2590 Disallow dropping nodes into themselves, ignore drag and drops less than 100ms, and deselect after dragging out
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/utils.js
  contentcuration/contentcuration/frontend/shared/views/draggable/DraggablePlaceholder.vue
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/__tests__/utils.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/constants.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/mutations.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/utils.js
Labels: UX, frontend, javascript, needs review
