Repository learningequality/studio, pull requests merged in 2020-06, with the labels that each got.

#1933 set the second nginx server block to be the default for port 8080.
  deploy/nginx.conf.jinja2
Labels: qa-ready

#1935 Sharing fixes
  contentcuration/contentcuration/frontend/shared/data/changes.js
  contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/index.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
  contentcuration/contentcuration/viewsets/user.py
Labels: qa-ready

#1940 Fix channel saving issues
  contentcuration/contentcuration/frontend/shared/data/changes.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
  contentcuration/contentcuration/viewsets/common.py
Labels: frontend, python, vueify

#1951 Google Tag Manager integration
  contentcuration/contentcuration/static/js/edit_channel/queue/views.js
  contentcuration/contentcuration/static/js/edit_channel/views.js
  contentcuration/contentcuration/static/js/utils/analytics.js
  contentcuration/contentcuration/templates/administration.html
  contentcuration/contentcuration/templates/base.html
  contentcuration/contentcuration/templates/channel_edit.html
  contentcuration/contentcuration/templates/channel_list.html
  contentcuration/contentcuration/templates/channel_not_found.html
  contentcuration/contentcuration/templates/exercise_edit.html
  contentcuration/contentcuration/templates/exercise_list.html
  contentcuration/contentcuration/templates/staging_not_found.html
  contentcuration/contentcuration/templates/unauthorized.html
  contentcuration/contentcuration/templates/unsupported_browser.html
Labels: UX, javascript, needs review, qa-ready

#1946 Don't swamp local changes on fetch
  contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
  contentcuration/contentcuration/frontend/shared/data/registry.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
Labels: needs review

#1955 Vue refactor administration (WIP)
  contentcuration/contentcuration/frontend/administration/__tests__/router.spec.js
  contentcuration/contentcuration/frontend/administration/components/ClipboardChip.vue
  contentcuration/contentcuration/frontend/administration/components/ConfirmationDialog.vue
  contentcuration/contentcuration/frontend/administration/constants.js
  contentcuration/contentcuration/frontend/administration/index.js
  contentcuration/contentcuration/frontend/administration/mixins.js
  contentcuration/contentcuration/frontend/administration/pages/AdministrationIndex.vue
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelActionsDropdown.vue
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelInfo.vue
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTableActions.vue
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTableHeader.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/EmailUsersDialog.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserActions.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserActionsDropdown.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserInfo.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserTable.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserTableActions.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserTableHeader.vue
  contentcuration/contentcuration/frontend/administration/pages/table.less
  contentcuration/contentcuration/frontend/administration/router.js
  contentcuration/contentcuration/frontend/administration/store.js
  contentcuration/contentcuration/frontend/administration/tableMixin.js
  contentcuration/contentcuration/frontend/administration/vuex/channelActions.js
  contentcuration/contentcuration/frontend/administration/vuex/channelInfo.js
  contentcuration/contentcuration/frontend/administration/vuex/channelTable.js
  contentcuration/contentcuration/frontend/administration/vuex/userActions.js
  contentcuration/contentcuration/frontend/administration/vuex/userInfo.js
  contentcuration/contentcuration/frontend/administration/vuex/userTable.js
  contentcuration/contentcuration/frontend/shared/views/MessageDialog.vue
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/templates/administration.html
  contentcuration/contentcuration/views/admin.py
  package.json
  setup.cfg
  webpack.config.js
Labels: WIP
