Repository learningequality/studio, pull requests merged in 2020-02, with the labels that each got.

#1767 Move servers to using Python 3
  contentcuration/contentcuration/dev_settings.py
  contentcuration/contentcuration/production_settings.py
  contentcuration/contentcuration/profile_settings.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tests/test_files.py
  contentcuration/contentcuration/tests/test_gcs_storage.py
  contentcuration/contentcuration/utils/gcs_storage.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/views/internal.py
  docker/Dockerfile.demo
  docker/Dockerfile.dev
  k8s/images/app/Dockerfile
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: needs review, qa-ready

#1769 remove probers from demo servers
  cloudbuild-pr.yaml
  k8s/templates/prober-deployment.yaml
  k8s/templates/prober-metrics-to-newrelic-cron-job.yaml
  k8s/templates/prober-service.yaml
Labels: qa-ready

#1771 Add globalsnackbar to channeleditindex
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
Labels: needs review

#1772 prototype of move modal
  contentcuration/contentcuration/frontend/channelEdit/move/MoveModal.vue
  contentcuration/contentcuration/frontend/channelEdit/move/NewTopicModal.vue
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/shared/views/BottomToolBar.vue
  contentcuration/contentcuration/frontend/shared/views/Sandbox.vue
Labels: qa-ready
