Repository learningequality/studio, pull requests merged in 2020-10, with the labels that each got.

#2344 Fix channel viewset for admins
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/viewsets/test_channel.py
  contentcuration/contentcuration/viewsets/channel.py
Labels: needs review

#2353 Different variable names for different values
  contentcuration/contentcuration/viewsets/base.py
Labels: bug, needs review

#2352 Prevent a new invitation being created after an old one is updated.
  contentcuration/contentcuration/tests/viewsets/test_invitation.py
  contentcuration/contentcuration/viewsets/invitation.py
Labels: needs review

#2358 Assign copyright_holder w/ @input & ensure mastery criteria is saved
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
Labels: needs review

#2346 Fix admin channel filter fields to not filter by invalid fields.
  contentcuration/contentcuration/tests/viewsets/test_channel.py
  contentcuration/contentcuration/viewsets/channel.py
Labels: needs review

#2356 Poll for unsynced changes then sync them
  contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
Labels: needs review

#2341 Markdown images as custom editor nodes
  contentcuration/contentcuration/frontend/shared/directives/click-outside.js
  contentcuration/contentcuration/frontend/shared/directives/mouse-move.js
  contentcuration/contentcuration/frontend/shared/directives/mouse-up.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownViewer/MarkdownViewer.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-html-to-md.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-md-to-html.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/markdownFormulaElement.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/markdownFormulaField.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/image-upload/image-html-to-md.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/image-upload/image-md-to-html.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/image-upload/markdownImageField.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/MarkdownFormula.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/MarkdownFormulaField.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formula-html-to-md.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formula-md-to-html.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formulas.css
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/MarkdownImageField.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-html-to-md.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-md-to-html.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-upload.css
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/index.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/style.less
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/registerCustomMarkdownField.js
  webpack.config.js
  yarn.lock
Labels: frontend, needs review

#2351 Clipboard fixes
  contentcuration/contentcuration/tests/base.py
  contentcuration/contentcuration/tests/viewsets/test_clipboard.py
  contentcuration/contentcuration/viewsets/clipboard.py
  contentcuration/contentcuration/viewsets/common.py
Labels: needs review

#2375 Handle extra fields being null.
  contentcuration/contentcuration/tests/viewsets/test_clipboard.py
  contentcuration/contentcuration/viewsets/common.py
Labels: needs review

#2359 Adding delayed calculation of annotation values for AdminUsers
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/utils/user.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/user.py
Labels: needs review

#2405 Add function for indexedDB clearing
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/index.js
Labels: needs review

#2363 Fix many to many field handling problems
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/data.js
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/getters.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/mutations.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetItem.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/__tests__/channelSetModal.spec.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/actions.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/getters.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/mutations.js
  contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/index.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
  contentcuration/contentcuration/tests/test_node_views.py
  contentcuration/contentcuration/tests/viewsets/test_channelset.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/tests/viewsets/test_user.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/nodes.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/channelset.py
  contentcuration/contentcuration/viewsets/common.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/invitation.py
  contentcuration/contentcuration/viewsets/sync/constants.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
  contentcuration/contentcuration/viewsets/user.py
Labels: needs review

#2350 Accepted invites not shown as invites on ChannelList anymore
  contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
  contentcuration/contentcuration/frontend/channelList/vuex/channelList/mutations.js
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharingTable.vue
  contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelSharingTable.spec.js
Labels: bug, needs review

#2421 Follow up fixes from Many to many field work
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/actions.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/mutations.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: needs review

#2420 Channel edit modal fields fixes
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Labels: needs review, qa-ready

#2426 Add login form banner message shown when authentication is needed to proceed
  contentcuration/contentcuration/frontend/accounts/pages/Main.vue
  contentcuration/contentcuration/frontend/accounts/pages/__tests__/main.spec.js
Labels: javascript, needs review

#2391 Wait for syncing to finish before trying to sync again.
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
Labels: needs review

#2425 Catch non-objects being passed to dot path mixin.
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/viewsets/common.py
Labels: needs review

#2427 Fix imported content original source links
  contentcuration/contentcuration/frontend/channelEdit/__tests__/utils.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/constants.js
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/utils.js
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
Labels: frontend, needs review

#2231 Add Draggable library and start integration (examples)
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeContextMenu.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/store.js
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/shared/mixins/draggable/base.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/collection.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/constants.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/handle.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/item.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/region.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.js
  contentcuration/contentcuration/frontend/shared/views/ContextMenuCloak.vue
  contentcuration/contentcuration/frontend/shared/views/draggable/DraggableCollection.vue
  contentcuration/contentcuration/frontend/shared/views/draggable/DraggableHandle.vue
  contentcuration/contentcuration/frontend/shared/views/draggable/DraggableItem.vue
  contentcuration/contentcuration/frontend/shared/views/draggable/DraggableRegion.vue
  contentcuration/contentcuration/frontend/shared/vuetify/theme.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/constants.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/mutations.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/mutations.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/utils.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/test/setup.js
Labels: qa-ready

#2440 Select All checkbox shows proper state during and after navigation
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Labels: needs review

#2441 Avoid error replacing route with same route
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Labels: needs review, qa-ready

#2432 Do a full recursive loading of requisite relations from indexedDB.
  contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
Labels: needs review

#2452 Array agg needs to know the field type
  contentcuration/contentcuration/viewsets/common.py
Labels: needs review, qa-ready

#2443 Updates to file uploading
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/store.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUpload.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadItem.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/contentNodeThumbnail.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/fileUpload.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/fileUploadItem.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/supplementaryItem.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/supplementaryList.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/thumbnailGenerator.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryItem.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ThumbnailGenerator.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/mixins.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/ImagesMenu/ImagesMenu.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelThumbnail.vue
  contentcuration/contentcuration/frontend/shared/views/files/FileStatus.vue
  contentcuration/contentcuration/frontend/shared/views/files/FileStatusText.vue
  contentcuration/contentcuration/frontend/shared/views/files/Uploader.vue
  contentcuration/contentcuration/frontend/shared/views/files/__tests__/fileStatus.spec.js
  contentcuration/contentcuration/frontend/shared/views/files/__tests__/fileStatusText.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/file/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/file/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/file/index.js
  contentcuration/contentcuration/frontend/shared/vuex/file/mutations.js
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/files.py
  contentcuration/contentcuration/viewsets/file.py
  package.json
  yarn.lock
Labels: needs review

#2449 ChannelSetModal fixes
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/__tests__/channelSetModal.spec.js
Labels: frontend, needs review

#2444 Import from channel card interaction improvements
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
Labels: needs review, qa-ready

#2328 Validation error errors | ResourcePanel & DetailsTabView
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/shared/utils/validation.js
Labels: needs review

#2480 Regenerate yarn.lock, get latest KDS
  yarn.lock
Labels: needs review

#2483 Add unit tests for extendSlot helper and make it more robust
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/handle.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.spec.js
  contentcuration/contentcuration/frontend/shared/views/ContextMenuCloak.vue
Labels: frontend, javascript, tech update / debt

#2475 file permissions
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/viewsets/test_file.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/file.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
Labels: needs review

#2485 Misc fixes to draggable state and components, and context menu fix
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/handle.js
  contentcuration/contentcuration/frontend/shared/views/ContextMenuCloak.vue
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/constants.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/index.js
  contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/mutations.js
Labels: javascript, needs review, tech update / debt

#2492 Permission unit testing, fixes, and query size reductions
  contentcuration/contentcuration/db/models/expressions.py
  contentcuration/contentcuration/db/models/functions.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/test_models.py
  contentcuration/contentcuration/tests/viewsets/test_channel.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/common.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/search/urls.py
Labels: needs review

#2491 Fixes async tasks
  contentcuration/contentcuration/db/models/manager.py
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ThumbnailGenerator.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressBar.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressBar.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
  contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/frontend/shared/utils/htmlScreenshot.js
  contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
  contentcuration/contentcuration/management/commands/exportchannel.py
  contentcuration/contentcuration/management/commands/get_channel_export.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/tests/test_asynctask.py
  contentcuration/contentcuration/tests/test_contentnodes.py
  contentcuration/contentcuration/tests/test_exportwriter.py
  contentcuration/contentcuration/tests/test_sync.py
  contentcuration/contentcuration/tests/test_task_api.py
  contentcuration/contentcuration/tests/views/test_views_internal.py
  contentcuration/contentcuration/tests/viewsets/test_channel.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/export_writer.py
  contentcuration/contentcuration/utils/files.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/utils/sync.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/views/channels.py
  contentcuration/contentcuration/views/files.py
  contentcuration/contentcuration/views/nodes.py
  contentcuration/contentcuration/views/zip.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/file.py
  contentcuration/contentcuration/viewsets/invitation.py
  contentcuration/contentcuration/viewsets/sync/constants.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
  contentcuration/contentcuration/viewsets/task.py
  requirements-dev.txt
  requirements.in
  requirements.txt
  webpack.config.js
Labels: needs review, qa-ready
