Repository learningequality/studio, pull requests merged in 2020-09, with the labels that each got.

#2166 Formulas plugin and MathQuill documentation
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/mathquill/mathquill.css
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/mathquill/mathquill.js
  docs/markdown_editor_viewer.md
Labels: frontend, needs review

#2176 Add some more error handling and logging to the image upload
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
Labels: frontend, needs review

#2161 disable the channel VSelect while loading during import from channels
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
Labels: needs review

#2184 File swapping fix
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditListItem.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadDefault.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadItem.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/contentNodeThumbnail.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/contentRenderer.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/fileUpload.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/fileUploadDefault.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SubtitlesList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ThumbnailCard.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ThumbnailGenerator.vue
  contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/files/Uploader.vue
  contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/file/getters.js
  contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/utils/files.py
  jest_config/jest.conf.js
  package.json
  yarn.lock
Labels: qa-ready

#2180 Allow adding text before a formula field when formula is a first entity in the markdown editor
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-html-to-md.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formula-html-to-md.js
Labels: frontend, needs review

#2186 Turn `ChannelItem` cards into real links
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
Labels: needs review

#2163 Channel creation bug fix - use diffTracker in commitChannel
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
Labels: needs review

#2193 Master into develop
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/tests/test_serializers.py
  contentcuration/contentcuration/viewsets/base.py
Labels: needs review

#2192 Fix copy to clipboard (again)
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Labels: frontend, needs review

#2183 Load staged channel in created() not route hook to show loader
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
  contentcuration/contentcuration/frontend/channelEdit/router.js
Labels: needs review

#2218 Channel thumbnails upload fix
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelThumbnail.vue
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
Labels: needs review

#2230 Don't repr valuesviewsets.
  contentcuration/contentcuration/viewsets/base.py
Labels: needs review

#2219 First pass vue component cleanup Resolves #2079
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
Labels: P1 - important, frontend

#2216 Fixed various styling and functional issues on edit modal
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemPreview/AssessmentItemPreview.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemToolbar.vue
  contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
  contentcuration/contentcuration/frontend/channelEdit/constants.js
  contentcuration/contentcuration/frontend/channelEdit/translator.js
  contentcuration/contentcuration/frontend/channelEdit/utils.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/contentNodeThumbnail.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
  contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/FormulasMenu/FormulasMenu.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/ImagesMenu/ImagesMenu.vue
  contentcuration/contentcuration/frontend/shared/views/MasteryDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
Labels: qa-ready

#2228 A couple misc. fixes
  contentcuration/contentcuration/templates/base.html
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
Labels: performance issue

#2221 Remove the tree viewset
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/TopicNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/mixins.js
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/NodeTreeNavigation.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/utils.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/getters.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/shared/client.js
  contentcuration/contentcuration/frontend/shared/data/changes.js
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/clipboard.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/sync/constants.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
  contentcuration/contentcuration/viewsets/tree.py
  contentcuration/search/viewsets/contentnode.py
Labels: needs review

#2248 Use native input and debounce it for text fields in content edit
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
Labels: frontend, needs review

#2253 Added saving indicator and debounced update function
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/SavingIndicator.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/editModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
Labels: qa-ready

#2240 Profiling
  README.md
  contentcuration/contentcuration/settings.py
  requirements-dev.in
  requirements-dev.txt
Labels: needs review, optimization

#2260 Optimize paginators
  contentcuration/contentcuration/migrations/0119_auto_20200915_1839.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/common.py
  contentcuration/contentcuration/viewsets/user.py
Labels: needs review, optimization, qa-ready

#2262 Fix iteration over empty `imageEls` for exercises without images
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
Labels: frontend, needs review

#2263 Added policy components
  contentcuration/contentcuration/decorators.py
  contentcuration/contentcuration/forms.py
  contentcuration/contentcuration/frontend/accounts/pages/Create.vue
  contentcuration/contentcuration/frontend/accounts/pages/__tests__/create.spec.js
  contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
  contentcuration/contentcuration/frontend/policies/index.js
  contentcuration/contentcuration/frontend/policies/pages/Policy.vue
  contentcuration/contentcuration/frontend/policies/router.js
  contentcuration/contentcuration/frontend/policies/store.js
  contentcuration/contentcuration/frontend/policies/vuex/index.js
  contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
  contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
  contentcuration/contentcuration/frontend/settings/pages/UsingStudio/index.vue
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/views/InfoModal.vue
  contentcuration/contentcuration/frontend/shared/views/ResponsiveDialog.vue
  contentcuration/contentcuration/frontend/shared/views/policies/CommunityStandardsModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PoliciesModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PolicyUpdates.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PrivacyPolicyModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/TermsOfServiceModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policiesModal.spec.js
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policyUpdates.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.spec.js
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/templates/policies/policy_accept.html
  contentcuration/contentcuration/templates/policies/text/boilerplate.html
  contentcuration/contentcuration/templates/policies/text/privacy_policy_2018_5_25.html
  contentcuration/contentcuration/templates/policies/text/terms_of_service.html
  contentcuration/contentcuration/tests/base.py
  contentcuration/contentcuration/tests/test_authentication.py
  contentcuration/contentcuration/tests/test_utils.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/policies.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/views/settings.py
  contentcuration/contentcuration/views/users.py
  webpack.config.js
Labels: qa-ready

#2271 remove index on modified and add it with desc sorting
  contentcuration/contentcuration/migrations/0120_auto_20200917_1912.py
  contentcuration/contentcuration/migrations/0121_auto_20200917_1912.py
  contentcuration/contentcuration/models.py
Labels: needs review, optimization

#2266 Maintain selections between channel tree view & edit modal
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/mutations.js
Labels: needs review

#2270 Change how we distinct content_ids to avoid a slow order_by
  contentcuration/contentcuration/viewsets/channel.py
Labels: needs review

#2259 Updates to assessment items backend
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/migrations/0122_assessment_id_index.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
  contentcuration/contentcuration/viewsets/assessmentitem.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/clipboard.py
  contentcuration/contentcuration/viewsets/common.py
  package.json
  yarn.lock
Labels: needs review

#2265 Somewhat optimize django page loading
  contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
  contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
  contentcuration/contentcuration/frontend/settings/pages/Storage/index.vue
  contentcuration/contentcuration/frontend/shared/views/CopyToken.vue
  contentcuration/contentcuration/frontend/shared/views/files/FileStorage.vue
  contentcuration/contentcuration/frontend/shared/views/files/Uploader.vue
  contentcuration/contentcuration/frontend/shared/views/files/__tests__/fileStorage.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/session/index.js
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/serializers.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/views/admin.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/views/settings.py
  contentcuration/contentcuration/views/users.py
  requirements.in
  requirements.txt
Labels: needs review, qa-ready

#2232 Markdown editor math rendering fixes
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-html-to-md.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/markdownFormulaElement.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/mathquill/mathquill.css
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/MarkdownFormula.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formula-html-to-md.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formula-md-to-html.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/style.less
  package.json
  yarn.lock
Labels: frontend, needs review, qa-ready

#2291 See previous & next resources in preview panel
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
Labels: needs review

#2290 Account & Storage Form Bugs
  contentcuration/contentcuration/frontend/settings/pages/Account/DeleteAccountForm.vue
  contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
  contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
Labels: needs review, qa-ready

#2292 Now you can leave the sharing modal no matter what
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
Labels: needs review

#2281 Add complete field to edit modal
  contentcuration/contentcuration/frontend/channelEdit/__tests__/utils.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemPreview/AssessmentItemPreview.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemPreview/AssessmentItemPreview.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentTab/AssessmentTab.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/HintsEditor/HintsEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/constants.js
  contentcuration/contentcuration/frontend/channelEdit/translator.js
  contentcuration/contentcuration/frontend/channelEdit/utils.js
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/__tests__/getters.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/__tests__/mutations.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/shared/__tests__/utils.spec.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/data/changes.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/translator.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.js
  contentcuration/contentcuration/frontend/shared/utils/helpers.spec.js
  contentcuration/contentcuration/frontend/shared/utils/validation.js
  contentcuration/contentcuration/frontend/shared/utils/validation.spec.js
  contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/MasteryDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelCatalogPrint.vue
  contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
Labels: frontend, needs review

#2278 Bubble changes on descendant updates/creation
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
Labels: qa-ready

#2288 Some more markdown math rendering fixes
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/markdownFormulaElement.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/MarkdownFormula.vue
Labels: frontend

#2251 Input question on AnswerEdit is now a type=number field
  contentcuration/contentcuration/frontend/channelEdit/__tests__/utils.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/utils.js
Labels: needs review

#2299 update numeric validation string
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
Labels: needs review

#2280 Icons, fonts, colors, oh my! Also, more Design System in Studio
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserTable.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/TopicNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SavedSearchesModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUpload.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelStar.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/channelItem.spec.js
  contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/star.spec.js
  contentcuration/contentcuration/frontend/shared/styles/main.less
  contentcuration/contentcuration/frontend/shared/views/AppBar.vue
  contentcuration/contentcuration/frontend/shared/views/IconButton.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelThumbnail.vue
  contentcuration/contentcuration/frontend/shared/views/details/Details.vue
  contentcuration/contentcuration/frontend/shared/views/form/Checkbox.vue
  contentcuration/contentcuration/frontend/shared/vuetify/theme.js
  contentcuration/contentcuration/templates/base.html
  contentcuration/contentcuration/templates/export/channel_detail_pdf.html
  contentcuration/contentcuration/templates/export/channel_detail_pdf_condensed.html
  contentcuration/contentcuration/templates/export/channels_pdf.html
  contentcuration/contentcuration/templates/unsupported_browser.html
  jest_config/jest.conf.js
  package.json
  webpack.config.js
  yarn.lock
Labels: needs review, qa-ready

#2298 Prevent errors when sync returns changes that are not persistable on the server
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: needs review

#2303 Don't try to get from None.
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: needs review

#2306 Add tests for unwriteable and empty updates and fix them.
  contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
  contentcuration/contentcuration/viewsets/base.py
Labels: needs review

#2093 Remove file auto delete signal to preserve files on GCS until further notice.
  contentcuration/contentcuration/models.py
Labels: needs review

#2329 Set IGNORED_SOURCE on transactions properly
  contentcuration/contentcuration/frontend/shared/data/resources.js
Labels: needs review

#2327 Properly reference assessmentitem ids.
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
Labels: needs review

#2330 Fix nested field updates for extra_fields.
  contentcuration/contentcuration/tests/viewsets/test_channel.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/viewsets/common.py
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: needs review

#2332 Use the images upload menu when an image dropped
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/ImagesMenu/ImagesMenu.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
Labels: frontend, needs review

#2277 Use pre-emptive locking to prevent tree corruption, and handle resulting deadlocks
  contentcuration/contentcuration/db/models/manager.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/ricecooker_versions.py
  contentcuration/contentcuration/test_settings.py
  contentcuration/contentcuration/tests/test_contentnodes.py
  contentcuration/contentcuration/tests/viewsets/__init__.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  requirements-dev.in
  requirements-dev.txt
Labels: needs review

#2336 More specs and documentation for markdown editor
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-html-to-md.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-md-to-html.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/image-upload/image-html-to-md.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/image-upload/image-md-to-html.spec.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-html-to-md.js
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-md-to-html.js
  docs/markdown_editor_viewer.md
Labels: frontend, needs review

#2340 Add permissions filtering for foreign key setting
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
  contentcuration/contentcuration/tests/viewsets/test_channelset.py
  contentcuration/contentcuration/tests/viewsets/test_file.py
  contentcuration/contentcuration/tests/viewsets/test_invitation.py
  contentcuration/contentcuration/tests/viewsets/test_user.py
  contentcuration/contentcuration/viewsets/assessmentitem.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/channelset.py
  contentcuration/contentcuration/viewsets/common.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/file.py
  contentcuration/contentcuration/viewsets/invitation.py
  contentcuration/contentcuration/viewsets/user.py
Labels: needs review

#2333 Cache channel metadata
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/utils/cache.py
  contentcuration/contentcuration/utils/channel.py
  contentcuration/contentcuration/viewsets/channel.py
Labels: needs review, optimization

#2337 Fix assessment item deletion transaction error
  contentcuration/contentcuration/frontend/shared/data/resources.js
Labels: needs review
