Repository learningequality/studio, pull requests merged in 2020-07, with the labels that each got.

#1962 Vue offline
  contentcuration/contentcuration/frontend/channelEdit/components/AddRelatedResourcesModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/move/MoveModal.vue
  contentcuration/contentcuration/frontend/channelEdit/move/__tests__/moveModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
  contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
  contentcuration/contentcuration/frontend/shared/views/FullscreenModal.vue
  contentcuration/contentcuration/frontend/shared/views/OfflineText.vue
  contentcuration/contentcuration/frontend/shared/views/__tests__/offlineText.spec.js
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Labels: qa-ready

#1984 Channel staging tree
  contentcuration/contentcuration/api.py
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/Diff/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/Diff/index.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/DiffTable.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/router.js
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/mutations.js
  contentcuration/contentcuration/frontend/shared/views/BottomBar.vue
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/views/internal.py
Labels: needs review, vueify

#1996 Edit channel app toolbars layout + staging tree toolbar
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
Labels: needs review, qa-ready, vueify

#2011 Fix helm argument error
  k8s/helm-deploy.sh
Labels: qa-ready

#2013 View-only mode updates + minor channel editor fixes
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/getters.js
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
  contentcuration/contentcuration/frontend/shared/views/Banner.vue
  contentcuration/contentcuration/frontend/shared/views/MainNavigationDrawer.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: qa-ready
