Repository learningequality/studio, pull requests merged in 2021-03, with the labels that each got.

#2970 Fix support for legacy clipboard nodes and Vuex handling for newer clipboard nodes
  .idea/studio.iml
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/mixins.js
  contentcuration/contentcuration/frontend/channelEdit/store.js
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/constants.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/index.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/utils.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/utils.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/utils/store2.js
  contentcuration/contentcuration/frontend/shared/vuex/baseStore.js
  contentcuration/contentcuration/frontend/shared/vuex/indexedDBPlugin/index.js
  contentcuration/contentcuration/frontend/shared/vuex/indexedDBPlugin/index.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/persistFactory.js
  contentcuration/contentcuration/frontend/shared/vuex/snackbar/index.js
  contentcuration/contentcuration/management/commands/setup.py
Labels: frontend, javascript, needs gherkin, needs review

#3008 Remove pagination code
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/channelList.spec.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/index.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
Labels: changelog

#3007 Filter out revoked/declined/accepted invitations when loading sharing page; delete invalid invitations when view-access is revoked
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharingTable.vue
  contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/getters.js
Labels: changelog

#2997 KDS to Studio: PublishModal
  contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/publish/__tests__/publishModal.spec.js
Labels: TODO: needs review

#3013 Content defaults reactivity fixes
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
  contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
  contentcuration/contentcuration/frontend/shared/views/form/__tests__/contentDefaults.spec.js
Labels: TODO: needs review

#3004 KDS to Studio: KModal on staging tree page
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
Labels: TODO: needs review

#3046 Merge down master
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
  contentcuration/contentcuration/viewsets/channel.py
Labels: TODO: needs review

#3043 Create tag relations one by one, and use CTEs to minimize queries doing so
  contentcuration/contentcuration/db/models/expressions.py
  contentcuration/contentcuration/db/models/query.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: DEV: backend, TODO: needs review

#3028 Async task fixes and new async calculation of resource size
  Makefile
  contentcuration/contentcuration/apps.py
  contentcuration/contentcuration/celery.py
  contentcuration/contentcuration/db/models/manager.py
  contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/publish/__tests__/publishModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
  contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/migrations/0121_auto_20210305_2028.py
  contentcuration/contentcuration/migrations/0122_file_modified_index.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/tasks_test.py
  contentcuration/contentcuration/tests/base.py
  contentcuration/contentcuration/tests/test_asynctask.py
  contentcuration/contentcuration/tests/test_task_api.py
  contentcuration/contentcuration/tests/utils/celery/__init__.py
  contentcuration/contentcuration/tests/utils/celery/test_tasks.py
  contentcuration/contentcuration/tests/utils/test_cache.py
  contentcuration/contentcuration/tests/utils/test_nodes.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/utils/cache.py
  contentcuration/contentcuration/utils/celery/__init__.py
  contentcuration/contentcuration/utils/celery/app.py
  contentcuration/contentcuration/utils/celery/signals.py
  contentcuration/contentcuration/utils/celery/tasks.py
  contentcuration/contentcuration/utils/nodes.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/utils/sync.py
  contentcuration/contentcuration/utils/tasks.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/common.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/file.py
  contentcuration/contentcuration/viewsets/task.py
  integration_testing/features/publish-channel.feature
  requirements.in
  requirements.txt
Labels: DEV: backend, TAG: dependencies, TODO: needs review
