Repository learningequality/studio, pull requests merged in 2021-01, with the labels that each got.

#2700 Multiple changes in node details calculation
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/views/nodes.py
  contentcuration/contentcuration/viewsets/common.py
Labels: needs review

#2694 Copy to parent of copied node with last-child position
  contentcuration/contentcuration/db/models/manager.py
  contentcuration/contentcuration/tests/test_contentnodes.py
Labels: needs review

#2628 Update privacy policy
  contentcuration/contentcuration/frontend/accounts/pages/Create.vue
  contentcuration/contentcuration/frontend/accounts/pages/Main.vue
  contentcuration/contentcuration/frontend/accounts/pages/__tests__/create.spec.js
  contentcuration/contentcuration/frontend/accounts/pages/__tests__/main.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
  contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
  contentcuration/contentcuration/frontend/settings/pages/UsingStudio/index.vue
  contentcuration/contentcuration/frontend/settings/pages/__tests__/usingStudio.spec.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/mixins/draggable/utils.js
  contentcuration/contentcuration/frontend/shared/views/ResponsiveDialog.vue
  contentcuration/contentcuration/frontend/shared/views/policies/CommunityStandardsModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PoliciesModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PolicyModals.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PolicyUpdates.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PrivacyPolicyModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/TermsOfServiceModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policiesModal.spec.js
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policyModals.spec.js
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policyUpdates.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/baseStore.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/plugin.js
Labels: needs review

#2695 Incomplete resources validation
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
Labels: needs review

#2699 Sync unsaved changes before leaving
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/shared/app.js
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/frontend/shared/translator.js
  contentcuration/contentcuration/frontend/shared/vuex/baseStore.js
  contentcuration/contentcuration/frontend/shared/vuex/session/index.js
  contentcuration/contentcuration/frontend/shared/vuex/syncProgressPlugin/index.js
  contentcuration/contentcuration/frontend/shared/vuex/syncProgressPlugin/syncProgressModule.js
Labels: needs review

#2714 V2 analytics
  .pre-commit-config.yaml
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemToolbar.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/HintsEditor/HintsEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditList.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FilePreview.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUpload.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SubtitlesList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryList.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelStar.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
  contentcuration/contentcuration/frontend/channelList/vuex/channelList/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
  contentcuration/contentcuration/frontend/shared/analytics/plugin.js
  contentcuration/contentcuration/frontend/shared/analytics/tagManager.js
  contentcuration/contentcuration/frontend/shared/analytics/tracker.js
  contentcuration/contentcuration/frontend/shared/app.js
  contentcuration/contentcuration/frontend/shared/views/CopyToken.vue
  contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/MainNavigationDrawer.vue
  contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
  contentcuration/contentcuration/frontend/shared/views/MasteryDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelTokenModal.vue
  contentcuration/contentcuration/frontend/shared/views/files/Uploader.vue
  jest_config/setup.js
Labels: frontend, javascript, needs review

#2748 Pass appropriate options to move
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
Labels: frontend, javascript, needs review

#2759 Run sync before publishing a channel
  contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue
  contentcuration/contentcuration/frontend/shared/app.js
Labels: needs review

#2675 remove autofilled title value from contentNode
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
Labels: needs review

#2842 Update the development setup script to reflect our `complete` validation strategy
  contentcuration/contentcuration/management/commands/setup.py
Labels: needs review

#2882 Don't calculate data when there are not resources in the channel
  contentcuration/contentcuration/models.py
Labels: needs review

#2858 Ensures nodes are loaded prior to copy, a use case for importing from search
  contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
  contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/tests/test_asynctask.py
  package.json
  yarn.lock
Labels: frontend, javascript, needs review

#2880 Fixed login case sensitivity
  contentcuration/contentcuration/forms.py
  contentcuration/contentcuration/migrations/0120_auto_20210128_1646.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/test_forms.py
  contentcuration/contentcuration/tests/test_models.py
  contentcuration/contentcuration/tests/views/test_users.py
  contentcuration/contentcuration/views/users.py
Labels: backend, python

#2879 add a promise to save and update everything in the difftracker before…
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
Labels: needs review
