Repository learningequality/studio, pull requests merged in 2021-05, with the labels that each got.

#3128 Add migration check to tests.
  .github/workflows/pythontest.yml
Labels: TODO: needs review

#3130 Enhance email regex to catch common errors
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharing.vue
  contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelSharing.spec.js
Labels: TODO: needs review

#3129 Feature flag support
  contentcuration/contentcuration/constants/__init__.py
  contentcuration/contentcuration/constants/feature_flags.py
  contentcuration/contentcuration/db/models/functions.py
  contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
  contentcuration/contentcuration/frontend/administration/vuex/userAdmin/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/administration/vuex/userAdmin/actions.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/vuex/session/index.js
  contentcuration/contentcuration/management/commands/garbage_collect.py
  contentcuration/contentcuration/migrations/0124_user_feature_flags.py
  contentcuration/contentcuration/migrations/0125_user_feature_flags_default.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/static/feature_flags.json
  contentcuration/contentcuration/tests/test_feature_flags.py
  contentcuration/contentcuration/tests/test_garbage_collect.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/garbage_collect.py
  contentcuration/contentcuration/views/admin.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/viewsets/user.py
  jest_config/jest.conf.js
  requirements-dev.txt
  requirements.in
  requirements.txt
  webpack.config.js
Labels: TODO: needs review

#3133 Added ES and FR translations for 'customContentAnswer'
  contentcuration/locale/CSV_FILES/contentcuration/locale/es_ES/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/fr_FR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
Labels: TAG: user strings, TODO: needs review

#2973 New feature: Add webm file format to Studio
  contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/filePreview.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/thumbnailGenerator.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ThumbnailGenerator.vue
  contentcuration/contentcuration/frontend/shared/leUtils/FormatPresets.js
  contentcuration/contentcuration/frontend/shared/leUtils/Languages.js
  contentcuration/contentcuration/frontend/shared/mixins.js
  contentcuration/contentcuration/frontend/shared/views/files/__tests__/uploader.spec.js
  contentcuration/contentcuration/migrations/0126_auto_20210219_2314.py
  contentcuration/contentcuration/migrations/0127_auto_20210504_1744.py
  contentcuration/contentcuration/tests/test_createchannel.py
  contentcuration/kolibri_content/migrations/0010_auto_20210202_0604.py
  contentcuration/kolibri_content/migrations/0011_auto_20210504_1744.py
  contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
  requirements-docs.txt
  requirements.in
  requirements.txt
Labels: TODO: needs gherkin update, TODO: needs user docs, changelog

#3137 User-scoped channel quiz feature
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/static/feature_flags.json
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: TAG: new feature, TAG: user strings, javascript

#3135 Copy translations for close button label
  contentcuration/locale/CSV_FILES/contentcuration/locale/ar_SA/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/es_ES/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/fr_FR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/hi_IN/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/pt_BR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
Labels: TAG: user strings, TODO: needs review

#3075 KDS to Studio: Replace ResponsiveDialog by KModal in InfoModal
  contentcuration/contentcuration/frontend/shared/views/InfoModal.vue
  contentcuration/contentcuration/frontend/shared/views/__tests__/infoModal.spec.js
  contentcuration/contentcuration/frontend/shared/views/__tests__/masteryDropdown.spec.js
  contentcuration/contentcuration/frontend/shared/views/__tests__/visibilityDropdown.spec.js
Labels: DEV: frontend, TAG: user strings

#3141 Merge down for Sprint release 2021-05-10
  contentcuration/contentcuration/tests/viewsets/test_user.py
  contentcuration/contentcuration/viewsets/user.py
  contentcuration/locale/CSV_FILES/contentcuration/locale/ar_SA/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/es_ES/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/fr_FR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/hi_IN/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/pt_BR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
Labels: TODO: needs review

#3142 Hotfixes release for sprint ending 2021-05-10
  .github/workflows/pythontest.yml
  LICENSE
  contentcuration/contentcuration/constants/__init__.py
  contentcuration/contentcuration/constants/feature_flags.py
  contentcuration/contentcuration/db/models/functions.py
  contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
  contentcuration/contentcuration/frontend/administration/vuex/userAdmin/__tests__/module.spec.js
  contentcuration/contentcuration/frontend/administration/vuex/userAdmin/actions.js
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/filePreview.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/thumbnailGenerator.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ThumbnailGenerator.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/leUtils/FormatPresets.js
  contentcuration/contentcuration/frontend/shared/leUtils/Languages.js
  contentcuration/contentcuration/frontend/shared/mixins.js
  contentcuration/contentcuration/frontend/shared/views/InfoModal.vue
  contentcuration/contentcuration/frontend/shared/views/__tests__/infoModal.spec.js
  contentcuration/contentcuration/frontend/shared/views/__tests__/masteryDropdown.spec.js
  contentcuration/contentcuration/frontend/shared/views/__tests__/visibilityDropdown.spec.js
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharing.vue
  contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelSharing.spec.js
  contentcuration/contentcuration/frontend/shared/views/files/__tests__/uploader.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/session/index.js
  contentcuration/contentcuration/management/commands/garbage_collect.py
  contentcuration/contentcuration/migrations/0124_user_feature_flags.py
  contentcuration/contentcuration/migrations/0125_user_feature_flags_default.py
  contentcuration/contentcuration/migrations/0126_auto_20210219_2314.py
  contentcuration/contentcuration/migrations/0127_auto_20210504_1744.py
  contentcuration/contentcuration/migrations/0128_auto_20210511_1605.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/static/feature_flags.json
  contentcuration/contentcuration/tests/test_createchannel.py
  contentcuration/contentcuration/tests/test_feature_flags.py
  contentcuration/contentcuration/tests/test_garbage_collect.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/garbage_collect.py
  contentcuration/contentcuration/views/admin.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/user.py
  contentcuration/kolibri_content/migrations/0010_auto_20210202_0604.py
  contentcuration/kolibri_content/migrations/0011_auto_20210504_1744.py
  contentcuration/kolibri_content/migrations/0012_auto_20210511_1605.py
  contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
  jest_config/jest.conf.js
  package.json
  requirements-dev.txt
  requirements-docs.txt
  requirements.in
  requirements.txt
  webpack.config.js
  yarn.lock
Labels: TODO: needs review

#2983 Add additional scenarios to gherkin for sync resources workflow
  integration_testing/features/sync-channel.feature
Labels: TAG: developer docs, TODO: needs updates, gherkin update

#3127 KDS to Studio: Use KModal in policy modals
  contentcuration/contentcuration/frontend/settings/pages/UsingStudio/index.vue
  contentcuration/contentcuration/frontend/shared/views/ResponsiveDialog.vue
  contentcuration/contentcuration/frontend/shared/views/policies/CommunityStandardsModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PoliciesModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PolicyModals.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PrivacyPolicyModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/TermsOfServiceModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policiesModal.spec.js
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policyModals.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/plugin.spec.js
Labels: DEV: frontend, TAG: user strings, TODO: needs review

#3154 Sprint release 2021-05-10 strings
  contentcuration/locale/CSV_FILES/contentcuration/locale/ar_SA/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/es_ES/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/fr_FR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/hi_IN/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/CSV_FILES/contentcuration/locale/pt_BR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
  contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
  contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
Labels: TODO: needs review

#3082 Gherkin Scenarios Updates
  integration_testing/features/README.md
  integration_testing/features/add-channel-to-starred.feature
  integration_testing/features/cancel-copy.feature
  integration_testing/features/change-language.feature
  integration_testing/features/copy-resource-via-right-click.feature
  integration_testing/features/copy-resource-via-selection-bar.feature
  integration_testing/features/copy-to-clipboard.feature
  integration_testing/features/create-a-channel.feature
  integration_testing/features/create-a-topic.feature
  integration_testing/features/create-account.feature
  integration_testing/features/create-exercise.feature
  integration_testing/features/delete-account.feature
  integration_testing/features/delete-channel.feature
  integration_testing/features/delete-resources.feature
  integration_testing/features/drag-drop-out-of-clipboard.feature
  integration_testing/features/drag-drop-to-clipboard.feature
  integration_testing/features/edit-account-information.feature
  integration_testing/features/edit-channel-details.feature
  integration_testing/features/edit-resource-details.feature
  integration_testing/features/expand-and-collapse-clipboard-topics.feature
  integration_testing/features/explore-without-an-account.feature
  integration_testing/features/export-account-information.feature
  integration_testing/features/get-channel-token-after-publishing.feature
  integration_testing/features/go-back-from-review-import-selections-to-channel-list.feature
  integration_testing/features/go-to-resource-original-location.feature
  integration_testing/features/import-content-from-another-channel.feature
  integration_testing/features/import-from-search-results-at-my-channels-channel-2.feature
  integration_testing/features/import-from-search-results-at-my-channels-channel.feature
  integration_testing/features/manage-additional-channel-options.feature
  integration_testing/features/move-resources-from-clipboard.feature
  integration_testing/features/move-resources.feature
  integration_testing/features/move-to-clipboard-via-right-click.feature
  integration_testing/features/open-a-channel-in-a-new-tab.feature
  integration_testing/features/open-sidebar-and-user-menus.feature
  integration_testing/features/preview-resource-in-clipboard.feature
  integration_testing/features/publish-channel.feature
  integration_testing/features/remove-from-clipboard-via-right-click.feature
  integration_testing/features/remove-from-clipboard-via-selection-bar.feature
  integration_testing/features/remove-multiple-resources-from-the-clipboard.feature
  integration_testing/features/remove-resource-from-channel.feature
  integration_testing/features/report-issue.feature
  integration_testing/features/request-more-storage-space.feature
  integration_testing/features/reset-your-password.feature
  integration_testing/features/resource-count-updates-properly.feature
  integration_testing/features/restore-resources-from-trash.feature
  integration_testing/features/review-import-selection-at-my-channels.feature
  integration_testing/features/review-used-storage.feature
  integration_testing/features/search-for-resources.feature
  integration_testing/features/share-channels.feature
  integration_testing/features/sync-channel.feature
  integration_testing/features/undo-removal-of-clipboard-resources.feature
  integration_testing/features/upload-files.feature
  integration_testing/features/url-updates.feature
  integration_testing/features/use-channels-with-view-only-access.feature
  integration_testing/features/view-channel-details.feature
  integration_testing/features/view-support-links.feature
Labels: gherkin update

#3177 Redirects using a reverse URL rather than hardcoded 'channels'
  contentcuration/contentcuration/frontend/accounts/pages/Main.vue
Labels: P0 - critical, TAG: regression, bug
