Repository learningequality/studio, pull requests merged in 2021-02, with the labels that each got.

#2893 Fix error preventing copying to clipboard
  contentcuration/contentcuration/frontend/shared/data/resources.js
Labels: P0 - critical, frontend, javascript, needs review

#2907 Fix call to get with unsupported parameters
  contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
Labels: javascript, needs review, python

#2915 Fix mark incomplete command for topics
  contentcuration/contentcuration/management/commands/mark_incomplete.py
Labels: needs review

#2901 Nodes selection and move modal fixes
  contentcuration/contentcuration/frontend/channelEdit/__tests__/CurrentTopicView.spec.js
  contentcuration/contentcuration/frontend/channelEdit/store.js
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
  contentcuration/contentcuration/frontend/shared/utils/testing.js
  jest_config/setup.js
Labels: javascript, needs review

#2948 Avoid left join when filtering for channel permissions
  contentcuration/contentcuration/models.py
Labels: needs review

#2957 Fix a linter issue (RouterNames -> RouteNames)
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
Labels: needs review

#2958 Add flower to dev dependencies
  README.md
  requirements-dev.in
  requirements-dev.txt
Labels: needs review

#2980 Replace VDialog with KModal in "Related resources tab"
  contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.vue
Labels: needs review

#2968 Migrate ProgressModal to KDS
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
Labels: needs review

#2986 Count every resource even if the content_id is repeated
  contentcuration/contentcuration/viewsets/channel.py
Labels: needs review

#2984 Replace PrimaryDialog with KModal (and remove it along with DialogBox)
  contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilterBar.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/channelItem.spec.js
  contentcuration/contentcuration/frontend/shared/views/DialogBox.vue
  contentcuration/contentcuration/frontend/shared/views/PrimaryDialog.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelTokenModal.vue
Labels: needs review, tech update / debt

#2992 Don't filter for ancestors if target is root node
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: backend, needs review, python

#2995 Disable the login button while the login request is running
  contentcuration/contentcuration/frontend/accounts/pages/Main.vue
Labels: needs review
