Repository learningequality/studio, pull requests merged in 2022-03, with the labels that each got.

#3328 Add metadata labels support to the backend
  contentcuration/contentcuration/migrations/0135_add_metadata_labels.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/kolibri_content/migrations/0018_auto_20220224_2031.py
  contentcuration/kolibri_content/models.py
Labels: TODO: needs review

#3331 Add error handling in updateTaskList to reduce constant logging of 403s
  contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
Labels: TODO: needs review

#3330 Draggable resize
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
Labels: DEV: frontend

#3334 Use EXISTS strategy for better performance
  contentcuration/contentcuration/models.py
Labels: TAG: tech update / debt, TAG: performance, TODO: needs review
