Repository learningequality/studio, pull requests merged in 2022-07, with the labels that each got.

#3442 Update django-cte to resolve query issue preventing access to API key
  contentcuration/contentcuration/apps.py
  contentcuration/contentcuration/management/commands/runserver.py
  requirements-dev.txt
  requirements-docs.txt
  requirements.in
  requirements.txt
Labels: TAG: dependencies, TODO: needs review, python

#3432 Master release for hotfixes completed before 2022-07-07
  .github/workflows/pythontest.yml
  .pre-commit-config.yaml
  Makefile
  README.md
  contentcuration/contentcuration/admin.py
  contentcuration/contentcuration/apps.py
  contentcuration/contentcuration/constants/contentnode.py
  contentcuration/contentcuration/dev_urls.py
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUpload.vue
  contentcuration/contentcuration/management/commands/loadconstants.py
  contentcuration/contentcuration/management/commands/runserver.py
  contentcuration/contentcuration/management/commands/set_default_learning_activities.py
  contentcuration/contentcuration/management/commands/set_file_duration.py
  contentcuration/contentcuration/management/commands/setup.py
  contentcuration/contentcuration/migrations/0131_auto_20210707_2326.py
  contentcuration/contentcuration/migrations/0132_auto_20210708_0011.py
  contentcuration/contentcuration/migrations/0133_auto_20220124_2149.py
  contentcuration/contentcuration/migrations/0134_alter_contentkind_kind.py
  contentcuration/contentcuration/migrations/0135_add_metadata_labels.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/permissions.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/celery/app.py
  contentcuration/contentcuration/utils/celery/tasks.py
  contentcuration/contentcuration/utils/minio_utils.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/utils/storage_common.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/views/files.py
  contentcuration/contentcuration/viewsets/file.py
  contentcuration/kolibri_content/migrations/0016_contentnode_duration.py
  contentcuration/kolibri_content/migrations/0017_alter_contentnode_kind.py
  contentcuration/kolibri_content/models.py
  docker-compose.yml
  docker/Dockerfile.demo
  docker/Dockerfile.dev
  docs/manual_setup.md
  k8s/images/app/Dockerfile
  package.json
  requirements-dev.in
  requirements-dev.txt
  requirements-docs.txt
  requirements.in
  requirements.txt
  yarn.lock
Labels: TODO: needs review

#3450 Add a conditional check for if user is an admin for channel sharing
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Labels: TODO: needs review

#3457 Production into unstable
  Makefile
  contentcuration/contentcuration/constants/contentnode.py
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUpload.vue
  contentcuration/contentcuration/management/commands/set_default_learning_activities.py
  contentcuration/contentcuration/management/commands/set_file_duration.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/utils/celery/app.py
  contentcuration/contentcuration/utils/celery/tasks.py
  contentcuration/contentcuration/utils/publish.py
  docker/Dockerfile.demo
  docker/Dockerfile.dev
  k8s/images/app/Dockerfile
  requirements-dev.txt
  requirements-docs.txt
  requirements.in
  requirements.txt
Labels: TODO: needs review

#3433 Initial websockets integration
  .github/workflows/pythontest.yml
  contentcuration/contentcuration/asgi.py
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tests/test_websocket_consumer.py
  contentcuration/contentcuration/viewsets/websockets/consumers.py
  contentcuration/contentcuration/viewsets/websockets/routing.py
  docker-compose.yml
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: TAG: new feature, TAG: dependencies, TODO: needs review, python

#3436 Add threshold field validation and properly handle updates to mastery models in all scenarios
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: TODO: needs review

#3410 Set complete marking on nodes created by ricecooker
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/tests/test_contentnodes.py
  contentcuration/contentcuration/tests/views/test_views_internal.py
  contentcuration/contentcuration/views/internal.py
Labels: TODO: needs review
