Repository learningequality/studio, pull requests merged in 2022-09, with the labels that each got.

#3593 Data migration updates
  Makefile
  contentcuration/contentcuration/management/commands/set_file_duration.py
  contentcuration/contentcuration/management/commands/set_orm_based_has_captions.py
Labels: TODO: needs review

#3602 adds translated user friendly string for files with no name
  contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadItem.vue
  contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/fileUploadItem.spec.js
Labels: TODO: needs review

#3609 Removes guest string
  contentcuration/contentcuration/frontend/shared/vuex/session/index.js
Labels: TODO: needs review

#3578 Topic metadata label updates
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
  contentcuration/contentcuration/tests/test_exportchannel.py
  contentcuration/contentcuration/utils/publish.py
Labels: TODO: needs review

#3613 Don't use variables for string keys
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
Labels: javascript

#3612 Default learning activities on upload for some content kinds
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/shared/leUtils/ContentKinds.js
Labels: TODO: needs review, javascript

#3636 Fix traceback handling for fake tasks
  contentcuration/contentcuration/viewsets/base.py
Labels: TODO: needs review

#3651 Add new models for full text search and migration commands
  Makefile
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tests/utils/test_cache.py
  contentcuration/contentcuration/tests/utils/test_nodes.py
  contentcuration/search/constants.py
  contentcuration/search/management/__init__.py
  contentcuration/search/management/commands/__init__.py
  contentcuration/search/management/commands/set_channel_tsvectors.py
  contentcuration/search/management/commands/set_contentnode_tsvectors.py
  contentcuration/search/migrations/0003_fulltextsearch.py
  contentcuration/search/models.py
Labels: TAG: new feature, TAG: tech update / debt, TAG: performance, TODO: needs review

#3639 Updates width of content library channel cards with no description to…
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
Labels: TAG: ux update

#3647 Add files existence and length check so validation is run later
  contentcuration/contentcuration/frontend/shared/utils/validation.js
  contentcuration/contentcuration/frontend/shared/utils/validation.spec.js
Labels: TODO: needs review

#3652 Patch release for preparing the release of metadata editing features
  Makefile
  contentcuration/contentcuration/management/commands/set_file_duration.py
  contentcuration/contentcuration/management/commands/set_orm_based_has_captions.py
  contentcuration/contentcuration/utils/gcs_storage.py
Labels: TODO: needs review

#3649 Hide tooltip for certain accessibility options and reorder them
  contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/accessibilityOptions.spec.js
  contentcuration/contentcuration/frontend/shared/constants.js
  integration_testing/features/wip-studio-edit-modal/wip-edit-accessibility-field.feature
Labels: TAG: ux update, TAG: unit tests, TODO: needs review

#3641 Refactor frontend-only fields and defensiveness
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentTab/AssessmentTab.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/__tests__/getters.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/utils.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/frontend/shared/vuex/indexedDBPlugin/index.js
Labels: TODO: needs review

#3671 Topic metadata updates
  contentcuration/contentcuration/tests/test_exportchannel.py
  contentcuration/contentcuration/utils/publish.py
Labels: TODO: needs review

#3670 Resolve issues affecting the bulk editing of new metadata fields
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
Labels: TODO: needs review

#3674 Resolve issue with selection mismatch between autocomplete and checkbox
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
Labels: P1 - important, TAG: new feature, TODO: needs review

#3685 Coerce all file durations with floor instead of ceil.
  contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
  contentcuration/contentcuration/tests/viewsets/test_file.py
  contentcuration/contentcuration/viewsets/file.py
Labels: TODO: needs review

#3687 Update IndexedDB mutations
  contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/mutations.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/mutations.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
  contentcuration/contentcuration/frontend/channelList/vuex/channelSet/mutations.js
  contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
  contentcuration/contentcuration/frontend/shared/vuex/file/mutations.js
  contentcuration/contentcuration/frontend/shared/vuex/session/index.js
Labels: TODO: needs review

#3697 Strings n things
  contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/accessibilityOptions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/activityDuration.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/resourcesNeededOptions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
  contentcuration/contentcuration/frontend/shared/mixins.js
  contentcuration/contentcuration/frontend/shared/translator.js
  contentcuration/contentcuration/frontend/shared/utils/validation.js
  contentcuration/contentcuration/frontend/shared/utils/validation.spec.js
Labels: TODO: needs review

#3684 Fix mastery criterion publishing
  contentcuration/contentcuration/tests/test_exportchannel.py
  contentcuration/contentcuration/tests/testdata.py
  contentcuration/contentcuration/utils/nodes.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: TODO: needs review

#3704 Fix metadata 'level' labeling
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
Labels: TODO: needs review

#3705 Updates to completion duration for references
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
  integration_testing/features/wip-studio-edit-modal/edit-completion-field.feature
Labels: TODO: needs review

#3679 Dropdown consolidation, layout fixes, and RTL updates
  contentcuration/contentcuration/frontend/accounts/pages/Create.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserStorage.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/LevelsOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/MasteryCriteriaGoal.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
  contentcuration/contentcuration/frontend/shared/styles/main.less
  contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharing.vue
  contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
  contentcuration/contentcuration/frontend/shared/views/form/CountryField.vue
  contentcuration/contentcuration/frontend/shared/views/form/DropdownWrapper.vue
  contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: TAG: ux update, TODO: needs review

#3698 Do existence check on navigator.clipboard
  contentcuration/contentcuration/frontend/administration/components/ClipboardChip.vue
  contentcuration/contentcuration/frontend/administration/components/__tests__/clipboardChip.spec.js
  contentcuration/contentcuration/frontend/shared/views/CopyToken.vue
  contentcuration/contentcuration/frontend/shared/views/errors/TechnicalTextBlock.vue
Labels: TODO: needs review
