Repository learningequality/studio, pull requests merged in 2022-08, with the labels that each got.

#3405 issue 3208: welcome new user email feature added
  contentcuration/contentcuration/templates/base.html
  contentcuration/contentcuration/templates/channel_list.html
  contentcuration/contentcuration/templates/channel_not_found.html
  contentcuration/contentcuration/templates/export/user_csv_email.txt
  contentcuration/contentcuration/templates/export/user_csv_email_subject.txt
  contentcuration/contentcuration/templates/permissions/permissions_email.html
  contentcuration/contentcuration/templates/permissions/permissions_email.txt
  contentcuration/contentcuration/templates/pwa/manifest.json
  contentcuration/contentcuration/templates/registration/activation_email.html
  contentcuration/contentcuration/templates/registration/activation_email.txt
  contentcuration/contentcuration/templates/registration/activation_email_subject.txt
  contentcuration/contentcuration/templates/registration/activation_needed_email.txt
  contentcuration/contentcuration/templates/registration/channel_published_email.txt
  contentcuration/contentcuration/templates/registration/getting_started.html
  contentcuration/contentcuration/templates/registration/password_reset_confirm.html
  contentcuration/contentcuration/templates/registration/password_reset_email.html
  contentcuration/contentcuration/templates/registration/password_reset_email.txt
  contentcuration/contentcuration/templates/registration/password_reset_form.html
  contentcuration/contentcuration/templates/registration/password_reset_subject.txt
  contentcuration/contentcuration/templates/registration/registration_needed_email.txt
  contentcuration/contentcuration/templates/registration/welcome_new_user_email.html
  contentcuration/contentcuration/templates/registration/welcome_new_user_email_subject.txt
  contentcuration/contentcuration/templates/settings/account_deleted_user_email.txt
  contentcuration/contentcuration/templates/settings/issue_report_email.txt
  contentcuration/contentcuration/templates/settings/storage_request_email.txt
  contentcuration/contentcuration/templates/staging_not_found.html
  contentcuration/contentcuration/templates/unauthorized.html
  contentcuration/contentcuration/templates/unsupported_browser.html
  contentcuration/contentcuration/views/users.py
Labels: TAG: user strings, TODO: needs review

#3344 Update tree view to include new metadata
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
  contentcuration/contentcuration/frontend/shared/mixins.js
  contentcuration/contentcuration/frontend/shared/views/ContentNodeLearningActivityIcon.vue
  contentcuration/contentcuration/frontend/shared/views/ToggleText.vue
  contentcuration/contentcuration/frontend/shared/views/__tests__/contentNodeLearningActivityIcon.spec.js
  contentcuration/contentcuration/frontend/shared/views/files/ImageOnlyThumbnail.vue
  contentcuration/contentcuration/frontend/shared/vuetify/icons.js
Labels: changelog, TAG: user strings

#3477 Ensure file duration is an integer
  contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
  contentcuration/contentcuration/tests/viewsets/test_file.py
  contentcuration/contentcuration/viewsets/file.py
Labels: TODO: needs review, python

#3475 Add reset and cleanup of dataLayer to prevent memory leaks
  contentcuration/contentcuration/frontend/shared/analytics/plugin.js
Labels: TAG: tech update / debt, TODO: needs review

#3476 Add missing coach icon to resource item, consolidate color of coach icon
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
  contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
  contentcuration/contentcuration/frontend/shared/vuetify/theme.js
Labels: TAG: ux update

#3332 Upgrade celery and use database backend for task results
  Makefile
  README.md
  contentcuration/contentcuration/apps.py
  contentcuration/contentcuration/celery.py
  contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/TaskProgress.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
  contentcuration/contentcuration/migrations/0139_django_celery_results.py
  contentcuration/contentcuration/migrations/0140_delete_task.py
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/not_production_settings.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tasks.py
  contentcuration/contentcuration/tasks_test.py
  contentcuration/contentcuration/tests/base.py
  contentcuration/contentcuration/tests/helpers.py
  contentcuration/contentcuration/tests/test_asynctask.py
  contentcuration/contentcuration/tests/test_exportchannel.py
  contentcuration/contentcuration/tests/test_node_views.py
  contentcuration/contentcuration/tests/test_utils.py
  contentcuration/contentcuration/tests/utils/celery/test_tasks.py
  contentcuration/contentcuration/tests/utils/test_cache.py
  contentcuration/contentcuration/tests/utils/test_garbage_collect.py
  contentcuration/contentcuration/tests/views/test_views_base.py
  contentcuration/contentcuration/tests/viewsets/base.py
  contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
  contentcuration/contentcuration/tests/viewsets/test_bookmark.py
  contentcuration/contentcuration/tests/viewsets/test_channel.py
  contentcuration/contentcuration/tests/viewsets/test_channelset.py
  contentcuration/contentcuration/tests/viewsets/test_clipboard.py
  contentcuration/contentcuration/tests/viewsets/test_contentnode.py
  contentcuration/contentcuration/tests/viewsets/test_file.py
  contentcuration/contentcuration/tests/viewsets/test_invitation.py
  contentcuration/contentcuration/tests/viewsets/test_user.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/celery/app.py
  contentcuration/contentcuration/utils/celery/signals.py
  contentcuration/contentcuration/utils/celery/tasks.py
  contentcuration/contentcuration/utils/garbage_collect.py
  contentcuration/contentcuration/utils/user.py
  contentcuration/contentcuration/views/admin.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/views/internal.py
  contentcuration/contentcuration/views/nodes.py
  contentcuration/contentcuration/views/settings.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/contentcuration/viewsets/contentnode.py
  contentcuration/contentcuration/viewsets/sync/endpoint.py
  deploy/probers/worker_probe.py
  package.json
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: TAG: tech update / debt, TAG: dependencies, TODO: needs review, python

#3482 Adjust the reset interval, and logic to prevent excess resets
  contentcuration/contentcuration/frontend/shared/analytics/plugin.js
Labels: TODO: needs review

#3485 Resolve remaining issues with dropdown positioning and broken help tooltips
  contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/LevelsOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/learningActivityOptions.spec.js
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/levelsOptions.spec.js
  contentcuration/contentcuration/frontend/shared/views/HelpTooltip.vue
  contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
  contentcuration/contentcuration/frontend/shared/views/__tests__/licenseDropdown.spec.js
  contentcuration/contentcuration/frontend/shared/views/__tests__/visibilityDropdown.spec.js
Labels: TAG: ux update, TODO: needs review

#3486 Always use the channel title for the first breadcrumb
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: TAG: ux update, TODO: needs review

#3480 Clean up frontend change tracker and snackbars related to undoing operations
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
  contentcuration/contentcuration/frontend/shared/data/changes.js
  contentcuration/contentcuration/frontend/shared/data/constants.js
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
Labels: TAG: tech update / debt, TAG: performance

#3562 Remove unneeded dependency for dead code
  contentcuration/contentcuration/utils/google_drive.py
  contentcuration/contentcuration/views/settings.py
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: TAG: tech update / debt, TAG: dependencies

#3561 Updates to studio documentation
  Makefile
  README.md
  docker/Dockerfile.dev
  docs/host_services_setup.md
  docs/manual_setup.md
  docs/running_tests.md
  package.json
Labels: TAG: developer docs

#3583 Update reference selection for duration for audioVideo resources
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
Labels: TODO: needs review

#3581 Remove deprecated Raven pip dependency.
  contentcuration/contentcuration/views/internal.py
  contentcuration/contentcuration/views/zip.py
  requirements.in
  requirements.txt
Labels: TODO: needs review

#3591 Add a check for new entries in the changes table to ensure swift syncing of non-Dexie observable changes.
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
Labels: TODO: needs review

#3592 Update sorting of channel items and fix erroneous use of `sortBy`
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
  contentcuration/contentcuration/frontend/shared/views/details/Details.vue
Labels: TODO: needs review
