Repository learningequality/studio, pull requests merged in 2023-03, with the labels that each got.

#3979 Device info updates
  contentcuration/contentcuration/urls.py
  contentcuration/kolibri_public/tests/test_public_v1_api.py
  contentcuration/kolibri_public/urls.py
  contentcuration/kolibri_public/views_v1.py
Labels: TODO: needs review

#3988 Propagate logout to all open tabs
  contentcuration/contentcuration/frontend/shared/data/index.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
Labels: TODO: needs review

#3712 Adds regression test for and fixes metadata label syncing.
  contentcuration/contentcuration/tests/test_sync.py
  contentcuration/contentcuration/utils/sync.py
Labels: TODO: needs updates

#3987 Channel metadata and import metadata public endpoints
  contentcuration/kolibri_content/constants/schema_versions.py
  contentcuration/kolibri_public/import_metadata_view.py
  contentcuration/kolibri_public/tests/test_content_app.py
  contentcuration/kolibri_public/tests/test_importmetadata_api.py
  contentcuration/kolibri_public/urls.py
  contentcuration/kolibri_public/views.py
  contentcuration/kolibri_public/views_v1.py
Labels: TODO: needs review

#3983 Add functionality for exporting published public channels to kolibri_public models
  contentcuration/contentcuration/db/models/manager.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/kolibri_public/management/__init__.py
  contentcuration/kolibri_public/management/commands/__init__.py
  contentcuration/kolibri_public/management/commands/export_channels_to_kolibri_public.py
  contentcuration/kolibri_public/migrations/0002_mptttreeidmanager.py
  contentcuration/kolibri_public/models.py
  contentcuration/kolibri_public/tests/base.py
  contentcuration/kolibri_public/tests/test_content_app.py
  contentcuration/kolibri_public/tests/test_mapper.py
  contentcuration/kolibri_public/utils/annotation.py
  contentcuration/kolibri_public/utils/mapper.py
Labels: TODO: needs review

#3991 Kolibri public v2 API endpoints
  contentcuration/contentcuration/db/models/manager.py
  contentcuration/contentcuration/middleware/locale.py
  contentcuration/contentcuration/middleware/session.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/urls.py
  contentcuration/contentcuration/utils/pagination.py
  contentcuration/contentcuration/utils/publish.py
  contentcuration/contentcuration/viewsets/base.py
  contentcuration/kolibri_content/base_models.py
  contentcuration/kolibri_content/constants/schema_versions.py
  contentcuration/kolibri_content/fields.py
  contentcuration/kolibri_content/migrations/0019_auto_20230207_0116.py
  contentcuration/kolibri_content/models.py
  contentcuration/kolibri_public/__init__.py
  contentcuration/kolibri_public/admin.py
  contentcuration/kolibri_public/apps.py
  contentcuration/kolibri_public/constants/stopwords-all.json
  contentcuration/kolibri_public/import_metadata_view.py
  contentcuration/kolibri_public/management/__init__.py
  contentcuration/kolibri_public/management/commands/__init__.py
  contentcuration/kolibri_public/management/commands/export_channels_to_kolibri_public.py
  contentcuration/kolibri_public/migrations/0001_initial.py
  contentcuration/kolibri_public/migrations/0002_mptttreeidmanager.py
  contentcuration/kolibri_public/migrations/__init__.py
  contentcuration/kolibri_public/models.py
  contentcuration/kolibri_public/search.py
  contentcuration/kolibri_public/stopwords.py
  contentcuration/kolibri_public/tests/base.py
  contentcuration/kolibri_public/tests/test_content_app.py
  contentcuration/kolibri_public/tests/test_importmetadata_api.py
  contentcuration/kolibri_public/tests/test_mapper.py
  contentcuration/kolibri_public/tests/test_public_v1_api.py
  contentcuration/kolibri_public/urls.py
  contentcuration/kolibri_public/utils/annotation.py
  contentcuration/kolibri_public/utils/mapper.py
  contentcuration/kolibri_public/views.py
  contentcuration/kolibri_public/views_v1.py
Labels: TODO: needs review

#3665 Run configuration for the devserver supported by Jetbrains/Intellij IDEs
  .gitignore
  .run/devserver.run.xml
Labels: TAG: dev experience

#3996 Migrate channel databases before import to guarantee compatible schema.
  contentcuration/kolibri_public/management/commands/export_channels_to_kolibri_public.py
Labels: TODO: needs review

#3999 Updates mp3 resource previewer metadata to include has captions and s…
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/accessibilityOptions.spec.js
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/management/commands/set_orm_based_has_captions.py
Labels: changelog
