Repository learningequality/studio, pull requests merged in 2023-04, with the labels that each got.

#3654 Initialize postgres docker container with developer defined SQL
  .docker/README.md
  .gitignore
  Makefile
  docker-compose.yml
Labels: TAG: dev experience, TAG: tech update / debt, TODO: needs review, DEV: dev-ops

#3990 Levels and categories in channel details modal
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/shared/constants.js
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
  contentcuration/contentcuration/frontend/shared/views/details/Details.vue
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/viewsets/common.py
Labels: TODO: needs review

#4018 Properly map language labels
  contentcuration/kolibri_public/search.py
  contentcuration/kolibri_public/tests/test_content_app.py
  requirements-dev.in
  requirements-dev.txt
Labels: TODO: needs review

#3984 Revert Celery Late Acknowledgement
  Makefile
  contentcuration/contentcuration/management/commands/reconcile_publishing_status.py
  contentcuration/contentcuration/utils/celery/app.py
  contentcuration/contentcuration/utils/celery/tasks.py
Labels: DEV: sysops, TAG: tech update / debt, DEV: backend, TAG: performance

#4022 Fix missing staging tree link in UI
  contentcuration/contentcuration/frontend/shared/views/ToolBar.vue
  contentcuration/contentcuration/viewsets/sync/utils.py
  package.json
Labels: changelog, DEV: backend, DEV: frontend, TAG: regression

#4016 Updates syncing metadata fields on syncing modal
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
  contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/data/serverSync.js
  contentcuration/contentcuration/tests/test_contentnodes.py
  contentcuration/contentcuration/tests/test_sync.py
  contentcuration/contentcuration/tests/viewsets/base.py
  contentcuration/contentcuration/utils/sync.py
  contentcuration/contentcuration/viewsets/channel.py
Labels: TODO: needs review

#4009 Disables "Move here" button in copy workflow once it has been clicked
  contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
Labels: TODO: needs review
