Repository learningequality/studio, pull requests merged in 2024-08, with the labels that each got.

#4614 Creates a regression test for and fixes duplicate node assessments returning a 500.
  contentcuration/contentcuration/tests/views/test_views_internal.py
  contentcuration/contentcuration/views/internal.py
Labels: TODO: needs review

#4629 Fix checkbox issues
  contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
  contentcuration/contentcuration/frontend/administration/pages/Users/UserTable.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
  contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemPreview/AssessmentItemPreview.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
  contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
  contentcuration/contentcuration/frontend/channelEdit/components/edit/EditList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
  contentcuration/contentcuration/frontend/channelList/views/Channel/components/LanguageFilter.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSelectionList.vue
  contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
  contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
Labels: TODO: needs review

#4604 Extract content urls
  contentcuration/automation/migrations/0001_initial.py
  contentcuration/automation/models.py
  contentcuration/automation/tests/appnexus/test_base.py
  contentcuration/automation/tests/test_recommendations_cache_model.py
  contentcuration/automation/utils/appnexus/base.py
  contentcuration/contentcuration/settings.py
  contentcuration/contentcuration/tests/utils/test_automation_manager.py
  contentcuration/contentcuration/tests/utils/test_recommendations.py
  contentcuration/contentcuration/utils/automation_manager.py
  contentcuration/contentcuration/utils/recommendations.py
Labels: TAG: new feature, DEV: backend, work-in-progress

#4353 Implement minimum length for passwords in account creation
  contentcuration/contentcuration/forms.py
  contentcuration/contentcuration/frontend/accounts/pages/Create.vue
  contentcuration/contentcuration/frontend/accounts/pages/__tests__/create.spec.js
  contentcuration/contentcuration/frontend/shared/translator.js
  contentcuration/contentcuration/frontend/shared/views/form/EmailField.vue
  contentcuration/contentcuration/frontend/shared/views/form/PasswordField.vue
  contentcuration/contentcuration/tests/test_settings.py
  contentcuration/contentcuration/tests/views/test_users.py
  contentcuration/contentcuration/views/users.py
Labels: TAG: user strings, TODO: needs review

#4609 Before entering Main, check for showPolicy query param to show policy
  contentcuration/contentcuration/frontend/accounts/pages/Create.vue
  contentcuration/contentcuration/frontend/accounts/pages/Main.vue
  contentcuration/contentcuration/frontend/settings/pages/UsingStudio/index.vue
  contentcuration/contentcuration/frontend/settings/pages/__tests__/usingStudio.spec.js
  contentcuration/contentcuration/frontend/shared/views/policies/PolicyModals.vue
  contentcuration/contentcuration/frontend/shared/views/policies/PrivacyPolicyModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/TermsOfServiceModal.vue
  contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policyModals.spec.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.js
  contentcuration/contentcuration/frontend/shared/vuex/policies/index.spec.js
Labels: TODO: needs review

#4677 Fixes the breadcrumb wrap for long folder names
  contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
Labels: bug, DEV: frontend, TODO: needs review

#4675 Fixes UI glitch on cards in collections
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelItem.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSelectionList.vue
  contentcuration/contentcuration/frontend/channelList/views/ChannelSet/__tests__/channelSelectionList.spec.js
Labels: DEV: frontend, TODO: needs review

#4668 (Change|Reset)Password components apply length validation
  contentcuration/contentcuration/frontend/accounts/pages/__tests__/resetPassword.spec.js
  contentcuration/contentcuration/frontend/accounts/pages/resetPassword/ResetPassword.vue
  contentcuration/contentcuration/frontend/settings/pages/Account/ChangePasswordForm.vue
Labels: TODO: needs review

#4686 Fix UI glitch with KSelect in Publish modal
  contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue
Labels: bug, DEV: frontend, TODO: needs review
