Repository learningequality/studio, pull requests merged in 2024-12, with the labels that each got.

#4842 Updates kds breaking changes
  contentcuration/contentcuration/frontend/RecommendedResourceCard/components/RecommendedResourceCard.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
  contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeValidator.vue
  contentcuration/contentcuration/frontend/shared/views/errors/TechnicalTextBlock.vue
  contentcuration/contentcuration/frontend/shared/vuetify/theme.js
  package.json
  yarn.lock
Labels: TAG: ux update, TODO: needs review

#4845 Fixes sorting order of trash items
  contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
Labels: bug, DEV: frontend, TODO: needs review

#4847 Optimize language existant query
  contentcuration/contentcuration/viewsets/channel.py
Labels: TAG: performance

#4833 Feat: added update-spreadsheet action
  .github/workflows/update-pr-spreadsheet.yml
Labels: TODO: needs review

#4856 Update `search-recommendations` with the latest code changes
  .github/workflows/update-pr-spreadsheet.yml
  contentcuration/contentcuration/apps.py
  contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
  contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
  contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
  contentcuration/contentcuration/frontend/shared/data/resources.js
  contentcuration/contentcuration/frontend/shared/mixins.js
  contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
  contentcuration/contentcuration/frontend/shared/views/details/Details.vue
  contentcuration/contentcuration/models.py
  contentcuration/contentcuration/signals.py
  contentcuration/contentcuration/tests/test_models.py
  contentcuration/contentcuration/tests/views/test_nodes.py
  contentcuration/contentcuration/tests/views/test_views_internal.py
  contentcuration/contentcuration/views/base.py
  contentcuration/contentcuration/views/internal.py
  contentcuration/contentcuration/views/nodes.py
  contentcuration/contentcuration/viewsets/channel.py
  contentcuration/kolibri_public/import_metadata_view.py
  contentcuration/kolibri_public/tests/test_content_app.py
  contentcuration/kolibri_public/tests/test_importmetadata_api.py
  contentcuration/kolibri_public/views.py
Labels: TODO: needs review
