Repository learningequality/studio, pull requests merged in 2024-07, with the labels that each got.

#4612 Fix saved search
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SavedSearchesModal.vue
  contentcuration/contentcuration/frontend/shared/data/resources.js
Labels: P1 - important

#4607 Update account deletion string
  contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
Labels: TAG: user strings, TODO: needs review

#4618 Fix incomplete resource importable
  contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
  contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
  contentcuration/contentcuration/viewsets/contentnode.py
Labels: TODO: needs review
